/// A consistent view of the state of the ledger

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: utxorpc/v1alpha/query/query.proto

package query

import (
	cardano "github.com/utxorpc/go-codegen/utxorpc/v1alpha/cardano"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a specific point in the blockchain.
type ChainPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`           // Slot number.
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`            // Block hash.
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`       // Block height.
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Block ms timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainPoint) Reset() {
	*x = ChainPoint{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainPoint) ProtoMessage() {}

func (x *ChainPoint) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainPoint.ProtoReflect.Descriptor instead.
func (*ChainPoint) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{0}
}

func (x *ChainPoint) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ChainPoint) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ChainPoint) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChainPoint) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AnyChainBlock struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NativeBytes []byte                 `protobuf:"bytes,1,opt,name=native_bytes,json=nativeBytes,proto3" json:"native_bytes,omitempty"` // Original bytes as defined by the chain
	// Types that are valid to be assigned to Chain:
	//
	//	*AnyChainBlock_Cardano
	Chain         isAnyChainBlock_Chain `protobuf_oneof:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainBlock) Reset() {
	*x = AnyChainBlock{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainBlock) ProtoMessage() {}

func (x *AnyChainBlock) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainBlock.ProtoReflect.Descriptor instead.
func (*AnyChainBlock) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{1}
}

func (x *AnyChainBlock) GetNativeBytes() []byte {
	if x != nil {
		return x.NativeBytes
	}
	return nil
}

func (x *AnyChainBlock) GetChain() isAnyChainBlock_Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *AnyChainBlock) GetCardano() *cardano.Block {
	if x != nil {
		if x, ok := x.Chain.(*AnyChainBlock_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyChainBlock_Chain interface {
	isAnyChainBlock_Chain()
}

type AnyChainBlock_Cardano struct {
	Cardano *cardano.Block `protobuf:"bytes,2,opt,name=cardano,proto3,oneof"` // A parsed Cardano block.
}

func (*AnyChainBlock_Cardano) isAnyChainBlock_Chain() {}

// Represents a reference to a transaction output
type TxoRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`    // Tx hash.
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // Output index.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxoRef) Reset() {
	*x = TxoRef{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxoRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxoRef) ProtoMessage() {}

func (x *TxoRef) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxoRef.ProtoReflect.Descriptor instead.
func (*TxoRef) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{2}
}

func (x *TxoRef) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TxoRef) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Request to get the chain parameters
type ReadParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields in the parsed response.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadParamsRequest) Reset() {
	*x = ReadParamsRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadParamsRequest) ProtoMessage() {}

func (x *ReadParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadParamsRequest.ProtoReflect.Descriptor instead.
func (*ReadParamsRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{3}
}

func (x *ReadParamsRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Request to get the chain config
type ReadGenesisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields in the parsed response.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadGenesisRequest) Reset() {
	*x = ReadGenesisRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGenesisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGenesisRequest) ProtoMessage() {}

func (x *ReadGenesisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGenesisRequest.ProtoReflect.Descriptor instead.
func (*ReadGenesisRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{4}
}

func (x *ReadGenesisRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Request to get the era summary
type ReadEraSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields in the parsed response.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEraSummaryRequest) Reset() {
	*x = ReadEraSummaryRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEraSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEraSummaryRequest) ProtoMessage() {}

func (x *ReadEraSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEraSummaryRequest.ProtoReflect.Descriptor instead.
func (*ReadEraSummaryRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{5}
}

func (x *ReadEraSummaryRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response containing the genesis configs
type ReadGenesisResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Genesis []byte                 `protobuf:"bytes,1,opt,name=genesis,proto3" json:"genesis,omitempty"` // genesis hash for the chain
	Caip2   string                 `protobuf:"bytes,2,opt,name=caip2,proto3" json:"caip2,omitempty"`     // the caip-2 ID for this network
	// Types that are valid to be assigned to Config:
	//
	//	*ReadGenesisResponse_Cardano
	Config        isReadGenesisResponse_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadGenesisResponse) Reset() {
	*x = ReadGenesisResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGenesisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGenesisResponse) ProtoMessage() {}

func (x *ReadGenesisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGenesisResponse.ProtoReflect.Descriptor instead.
func (*ReadGenesisResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{6}
}

func (x *ReadGenesisResponse) GetGenesis() []byte {
	if x != nil {
		return x.Genesis
	}
	return nil
}

func (x *ReadGenesisResponse) GetCaip2() string {
	if x != nil {
		return x.Caip2
	}
	return ""
}

func (x *ReadGenesisResponse) GetConfig() isReadGenesisResponse_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ReadGenesisResponse) GetCardano() *cardano.Genesis {
	if x != nil {
		if x, ok := x.Config.(*ReadGenesisResponse_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isReadGenesisResponse_Config interface {
	isReadGenesisResponse_Config()
}

type ReadGenesisResponse_Cardano struct {
	Cardano *cardano.Genesis `protobuf:"bytes,3,opt,name=cardano,proto3,oneof"` // Cardano genesis
}

func (*ReadGenesisResponse_Cardano) isReadGenesisResponse_Config() {}

// Response containing the era summaries
type ReadEraSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Summary:
	//
	//	*ReadEraSummaryResponse_Cardano
	Summary       isReadEraSummaryResponse_Summary `protobuf_oneof:"summary"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEraSummaryResponse) Reset() {
	*x = ReadEraSummaryResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEraSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEraSummaryResponse) ProtoMessage() {}

func (x *ReadEraSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEraSummaryResponse.ProtoReflect.Descriptor instead.
func (*ReadEraSummaryResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{7}
}

func (x *ReadEraSummaryResponse) GetSummary() isReadEraSummaryResponse_Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ReadEraSummaryResponse) GetCardano() *cardano.EraSummaries {
	if x != nil {
		if x, ok := x.Summary.(*ReadEraSummaryResponse_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isReadEraSummaryResponse_Summary interface {
	isReadEraSummaryResponse_Summary()
}

type ReadEraSummaryResponse_Cardano struct {
	Cardano *cardano.EraSummaries `protobuf:"bytes,1,opt,name=cardano,proto3,oneof"` // Cardano era summaries
}

func (*ReadEraSummaryResponse_Cardano) isReadEraSummaryResponse_Summary() {}

// An evenlope that holds parameter data from any of the compatible chains
type AnyChainParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Params:
	//
	//	*AnyChainParams_Cardano
	Params        isAnyChainParams_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainParams) Reset() {
	*x = AnyChainParams{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainParams) ProtoMessage() {}

func (x *AnyChainParams) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainParams.ProtoReflect.Descriptor instead.
func (*AnyChainParams) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{8}
}

func (x *AnyChainParams) GetParams() isAnyChainParams_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AnyChainParams) GetCardano() *cardano.PParams {
	if x != nil {
		if x, ok := x.Params.(*AnyChainParams_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyChainParams_Params interface {
	isAnyChainParams_Params()
}

type AnyChainParams_Cardano struct {
	Cardano *cardano.PParams `protobuf:"bytes,1,opt,name=cardano,proto3,oneof"` // Cardano parameters
}

func (*AnyChainParams_Cardano) isAnyChainParams_Params() {}

// Response containing the chain parameters
type ReadParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *AnyChainParams        `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`                        // The value of the parameters.
	LedgerTip     *ChainPoint            `protobuf:"bytes,2,opt,name=ledger_tip,json=ledgerTip,proto3" json:"ledger_tip,omitempty"` // The chain point that represent the ledger current position.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadParamsResponse) Reset() {
	*x = ReadParamsResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadParamsResponse) ProtoMessage() {}

func (x *ReadParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadParamsResponse.ProtoReflect.Descriptor instead.
func (*ReadParamsResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{9}
}

func (x *ReadParamsResponse) GetValues() *AnyChainParams {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ReadParamsResponse) GetLedgerTip() *ChainPoint {
	if x != nil {
		return x.LedgerTip
	}
	return nil
}

// An evenlope that holds an UTxO patterns from any of compatible chains
type AnyUtxoPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to UtxoPattern:
	//
	//	*AnyUtxoPattern_Cardano
	UtxoPattern   isAnyUtxoPattern_UtxoPattern `protobuf_oneof:"utxo_pattern"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyUtxoPattern) Reset() {
	*x = AnyUtxoPattern{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyUtxoPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyUtxoPattern) ProtoMessage() {}

func (x *AnyUtxoPattern) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyUtxoPattern.ProtoReflect.Descriptor instead.
func (*AnyUtxoPattern) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{10}
}

func (x *AnyUtxoPattern) GetUtxoPattern() isAnyUtxoPattern_UtxoPattern {
	if x != nil {
		return x.UtxoPattern
	}
	return nil
}

func (x *AnyUtxoPattern) GetCardano() *cardano.TxOutputPattern {
	if x != nil {
		if x, ok := x.UtxoPattern.(*AnyUtxoPattern_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyUtxoPattern_UtxoPattern interface {
	isAnyUtxoPattern_UtxoPattern()
}

type AnyUtxoPattern_Cardano struct {
	Cardano *cardano.TxOutputPattern `protobuf:"bytes,1,opt,name=cardano,proto3,oneof"`
}

func (*AnyUtxoPattern_Cardano) isAnyUtxoPattern_UtxoPattern() {}

// Represents a simple utxo predicate that can composed to create more complex ones
type UtxoPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *AnyUtxoPattern        `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`              // Predicate is true if tx exhibits pattern.
	Not           []*UtxoPredicate       `protobuf:"bytes,2,rep,name=not,proto3" json:"not,omitempty"`                  // Predicate is true if tx doesn't exhibit pattern.
	AllOf         []*UtxoPredicate       `protobuf:"bytes,3,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"` // Predicate is true if utxo exhibits all of the patterns.
	AnyOf         []*UtxoPredicate       `protobuf:"bytes,4,rep,name=any_of,json=anyOf,proto3" json:"any_of,omitempty"` // Predicate is true if utxo exhibits any of the patterns.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxoPredicate) Reset() {
	*x = UtxoPredicate{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoPredicate) ProtoMessage() {}

func (x *UtxoPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoPredicate.ProtoReflect.Descriptor instead.
func (*UtxoPredicate) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{11}
}

func (x *UtxoPredicate) GetMatch() *AnyUtxoPattern {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *UtxoPredicate) GetNot() []*UtxoPredicate {
	if x != nil {
		return x.Not
	}
	return nil
}

func (x *UtxoPredicate) GetAllOf() []*UtxoPredicate {
	if x != nil {
		return x.AllOf
	}
	return nil
}

func (x *UtxoPredicate) GetAnyOf() []*UtxoPredicate {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

// An evenlope that holds an UTxO from any of compatible chains
type AnyUtxoData struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NativeBytes []byte                 `protobuf:"bytes,1,opt,name=native_bytes,json=nativeBytes,proto3" json:"native_bytes,omitempty"` // Original bytes as defined by the chain
	TxoRef      *TxoRef                `protobuf:"bytes,2,opt,name=txo_ref,json=txoRef,proto3" json:"txo_ref,omitempty"`                // Hash of the previous transaction.
	// Types that are valid to be assigned to ParsedState:
	//
	//	*AnyUtxoData_Cardano
	ParsedState   isAnyUtxoData_ParsedState `protobuf_oneof:"parsed_state"`
	BlockRef      *ChainPoint               `protobuf:"bytes,4,opt,name=block_ref,json=blockRef,proto3" json:"block_ref,omitempty"` // The chain point that represents the block this UTxO was created in.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyUtxoData) Reset() {
	*x = AnyUtxoData{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyUtxoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyUtxoData) ProtoMessage() {}

func (x *AnyUtxoData) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyUtxoData.ProtoReflect.Descriptor instead.
func (*AnyUtxoData) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{12}
}

func (x *AnyUtxoData) GetNativeBytes() []byte {
	if x != nil {
		return x.NativeBytes
	}
	return nil
}

func (x *AnyUtxoData) GetTxoRef() *TxoRef {
	if x != nil {
		return x.TxoRef
	}
	return nil
}

func (x *AnyUtxoData) GetParsedState() isAnyUtxoData_ParsedState {
	if x != nil {
		return x.ParsedState
	}
	return nil
}

func (x *AnyUtxoData) GetCardano() *cardano.TxOutput {
	if x != nil {
		if x, ok := x.ParsedState.(*AnyUtxoData_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

func (x *AnyUtxoData) GetBlockRef() *ChainPoint {
	if x != nil {
		return x.BlockRef
	}
	return nil
}

type isAnyUtxoData_ParsedState interface {
	isAnyUtxoData_ParsedState()
}

type AnyUtxoData_Cardano struct {
	Cardano *cardano.TxOutput `protobuf:"bytes,3,opt,name=cardano,proto3,oneof"` // A cardano UTxO
}

func (*AnyUtxoData_Cardano) isAnyUtxoData_ParsedState() {}

// Request to get specific UTxOs
type ReadUtxosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*TxoRef              `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`                            // List of keys UTxOs.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUtxosRequest) Reset() {
	*x = ReadUtxosRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUtxosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUtxosRequest) ProtoMessage() {}

func (x *ReadUtxosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUtxosRequest.ProtoReflect.Descriptor instead.
func (*ReadUtxosRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{13}
}

func (x *ReadUtxosRequest) GetKeys() []*TxoRef {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ReadUtxosRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response containing the UTxOs associated with the requested addresses.
type ReadUtxosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnyUtxoData         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                          // List of UTxOs.
	LedgerTip     *ChainPoint            `protobuf:"bytes,2,opt,name=ledger_tip,json=ledgerTip,proto3" json:"ledger_tip,omitempty"` // The chain point that represent the ledger current position.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUtxosResponse) Reset() {
	*x = ReadUtxosResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUtxosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUtxosResponse) ProtoMessage() {}

func (x *ReadUtxosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUtxosResponse.ProtoReflect.Descriptor instead.
func (*ReadUtxosResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{14}
}

func (x *ReadUtxosResponse) GetItems() []*AnyUtxoData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReadUtxosResponse) GetLedgerTip() *ChainPoint {
	if x != nil {
		return x.LedgerTip
	}
	return nil
}

// Request to search for UTxO based on a pattern.
type SearchUtxosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predicate     *UtxoPredicate         `protobuf:"bytes,1,opt,name=predicate,proto3" json:"predicate,omitempty"`                     // Pattern to match UTxOs by.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`    // Field mask to selectively return fields.
	MaxItems      int32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`      // The maximum number of items to return.
	StartToken    string                 `protobuf:"bytes,4,opt,name=start_token,json=startToken,proto3" json:"start_token,omitempty"` // The next_page_token value returned from a previous request, if any.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUtxosRequest) Reset() {
	*x = SearchUtxosRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUtxosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUtxosRequest) ProtoMessage() {}

func (x *SearchUtxosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUtxosRequest.ProtoReflect.Descriptor instead.
func (*SearchUtxosRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{15}
}

func (x *SearchUtxosRequest) GetPredicate() *UtxoPredicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *SearchUtxosRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *SearchUtxosRequest) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *SearchUtxosRequest) GetStartToken() string {
	if x != nil {
		return x.StartToken
	}
	return ""
}

// Response containing the UTxOs that match the requested addresses.
type SearchUtxosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnyUtxoData         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                          // List of UTxOs.
	LedgerTip     *ChainPoint            `protobuf:"bytes,2,opt,name=ledger_tip,json=ledgerTip,proto3" json:"ledger_tip,omitempty"` // The chain point that represent the ledger current position.
	NextToken     string                 `protobuf:"bytes,3,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"` // Token to retrieve the next page of results, or empty if there are no more results.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUtxosResponse) Reset() {
	*x = SearchUtxosResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUtxosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUtxosResponse) ProtoMessage() {}

func (x *SearchUtxosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUtxosResponse.ProtoReflect.Descriptor instead.
func (*SearchUtxosResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{16}
}

func (x *SearchUtxosResponse) GetItems() []*AnyUtxoData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchUtxosResponse) GetLedgerTip() *ChainPoint {
	if x != nil {
		return x.LedgerTip
	}
	return nil
}

func (x *SearchUtxosResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

// Request to get data (as in plural of datum)
type ReadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          [][]byte               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields in the response.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataRequest) Reset() {
	*x = ReadDataRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataRequest) ProtoMessage() {}

func (x *ReadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataRequest.ProtoReflect.Descriptor instead.
func (*ReadDataRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{17}
}

func (x *ReadDataRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ReadDataRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// An evenlope that holds a datum for any of the compatible chains
type AnyChainDatum struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NativeBytes []byte                 `protobuf:"bytes,1,opt,name=native_bytes,json=nativeBytes,proto3" json:"native_bytes,omitempty"` // Original bytes as defined by the chain
	Key         []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to ParsedState:
	//
	//	*AnyChainDatum_Cardano
	ParsedState   isAnyChainDatum_ParsedState `protobuf_oneof:"parsed_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainDatum) Reset() {
	*x = AnyChainDatum{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainDatum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainDatum) ProtoMessage() {}

func (x *AnyChainDatum) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainDatum.ProtoReflect.Descriptor instead.
func (*AnyChainDatum) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{18}
}

func (x *AnyChainDatum) GetNativeBytes() []byte {
	if x != nil {
		return x.NativeBytes
	}
	return nil
}

func (x *AnyChainDatum) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AnyChainDatum) GetParsedState() isAnyChainDatum_ParsedState {
	if x != nil {
		return x.ParsedState
	}
	return nil
}

func (x *AnyChainDatum) GetCardano() *cardano.PlutusData {
	if x != nil {
		if x, ok := x.ParsedState.(*AnyChainDatum_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyChainDatum_ParsedState interface {
	isAnyChainDatum_ParsedState()
}

type AnyChainDatum_Cardano struct {
	Cardano *cardano.PlutusData `protobuf:"bytes,3,opt,name=cardano,proto3,oneof"` // A cardano UTxO
}

func (*AnyChainDatum_Cardano) isAnyChainDatum_ParsedState() {}

// Response containing data (as in plural of datum)
type ReadDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AnyChainDatum       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`                        // The value of each datum.
	LedgerTip     *ChainPoint            `protobuf:"bytes,2,opt,name=ledger_tip,json=ledgerTip,proto3" json:"ledger_tip,omitempty"` // The chain point that represent the ledger current position.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataResponse) Reset() {
	*x = ReadDataResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataResponse) ProtoMessage() {}

func (x *ReadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataResponse.ProtoReflect.Descriptor instead.
func (*ReadDataResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{19}
}

func (x *ReadDataResponse) GetValues() []*AnyChainDatum {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ReadDataResponse) GetLedgerTip() *ChainPoint {
	if x != nil {
		return x.LedgerTip
	}
	return nil
}

// Request to get a transaction by hash
type ReadTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                            // The hash of the transaction.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields in the response.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTxRequest) Reset() {
	*x = ReadTxRequest{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTxRequest) ProtoMessage() {}

func (x *ReadTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTxRequest.ProtoReflect.Descriptor instead.
func (*ReadTxRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{20}
}

func (x *ReadTxRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReadTxRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Represents a transaction from any supported blockchain.
type AnyChainTx struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NativeBytes []byte                 `protobuf:"bytes,1,opt,name=native_bytes,json=nativeBytes,proto3" json:"native_bytes,omitempty"` // Original bytes as defined by the chain
	// Types that are valid to be assigned to Chain:
	//
	//	*AnyChainTx_Cardano
	Chain         isAnyChainTx_Chain `protobuf_oneof:"chain"`
	BlockRef      *ChainPoint        `protobuf:"bytes,3,opt,name=block_ref,json=blockRef,proto3" json:"block_ref,omitempty"` // The chain point that represents the block this transaction belongs to.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainTx) Reset() {
	*x = AnyChainTx{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainTx) ProtoMessage() {}

func (x *AnyChainTx) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainTx.ProtoReflect.Descriptor instead.
func (*AnyChainTx) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{21}
}

func (x *AnyChainTx) GetNativeBytes() []byte {
	if x != nil {
		return x.NativeBytes
	}
	return nil
}

func (x *AnyChainTx) GetChain() isAnyChainTx_Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *AnyChainTx) GetCardano() *cardano.Tx {
	if x != nil {
		if x, ok := x.Chain.(*AnyChainTx_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

func (x *AnyChainTx) GetBlockRef() *ChainPoint {
	if x != nil {
		return x.BlockRef
	}
	return nil
}

type isAnyChainTx_Chain interface {
	isAnyChainTx_Chain()
}

type AnyChainTx_Cardano struct {
	Cardano *cardano.Tx `protobuf:"bytes,2,opt,name=cardano,proto3,oneof"` // A Cardano transaction.
}

func (*AnyChainTx_Cardano) isAnyChainTx_Chain() {}

// Response containing the transaction associated with the requested hash.
type ReadTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *AnyChainTx            `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`                                // The transaction.
	LedgerTip     *ChainPoint            `protobuf:"bytes,2,opt,name=ledger_tip,json=ledgerTip,proto3" json:"ledger_tip,omitempty"` // The chain point that represent the ledger current position.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTxResponse) Reset() {
	*x = ReadTxResponse{}
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTxResponse) ProtoMessage() {}

func (x *ReadTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_query_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTxResponse.ProtoReflect.Descriptor instead.
func (*ReadTxResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_query_query_proto_rawDescGZIP(), []int{22}
}

func (x *ReadTxResponse) GetTx() *AnyChainTx {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *ReadTxResponse) GetLedgerTip() *ChainPoint {
	if x != nil {
		return x.LedgerTip
	}
	return nil
}

var File_utxorpc_v1alpha_query_query_proto protoreflect.FileDescriptor

const file_utxorpc_v1alpha_query_query_proto_rawDesc = "" +
	"\n" +
	"!utxorpc/v1alpha/query/query.proto\x12\x15utxorpc.v1alpha.query\x1a google/protobuf/field_mask.proto\x1a%utxorpc/v1alpha/cardano/cardano.proto\"j\n" +
	"\n" +
	"ChainPoint\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"w\n" +
	"\rAnyChainBlock\x12!\n" +
	"\fnative_bytes\x18\x01 \x01(\fR\vnativeBytes\x12:\n" +
	"\acardano\x18\x02 \x01(\v2\x1e.utxorpc.v1alpha.cardano.BlockH\x00R\acardanoB\a\n" +
	"\x05chain\"2\n" +
	"\x06TxoRef\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"N\n" +
	"\x11ReadParamsRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"O\n" +
	"\x12ReadGenesisRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"R\n" +
	"\x15ReadEraSummaryRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x8d\x01\n" +
	"\x13ReadGenesisResponse\x12\x18\n" +
	"\agenesis\x18\x01 \x01(\fR\agenesis\x12\x14\n" +
	"\x05caip2\x18\x02 \x01(\tR\x05caip2\x12<\n" +
	"\acardano\x18\x03 \x01(\v2 .utxorpc.v1alpha.cardano.GenesisH\x00R\acardanoB\b\n" +
	"\x06config\"f\n" +
	"\x16ReadEraSummaryResponse\x12A\n" +
	"\acardano\x18\x01 \x01(\v2%.utxorpc.v1alpha.cardano.EraSummariesH\x00R\acardanoB\t\n" +
	"\asummary\"X\n" +
	"\x0eAnyChainParams\x12<\n" +
	"\acardano\x18\x01 \x01(\v2 .utxorpc.v1alpha.cardano.PParamsH\x00R\acardanoB\b\n" +
	"\x06params\"\x95\x01\n" +
	"\x12ReadParamsResponse\x12=\n" +
	"\x06values\x18\x01 \x01(\v2%.utxorpc.v1alpha.query.AnyChainParamsR\x06values\x12@\n" +
	"\n" +
	"ledger_tip\x18\x02 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\tledgerTip\"f\n" +
	"\x0eAnyUtxoPattern\x12D\n" +
	"\acardano\x18\x01 \x01(\v2(.utxorpc.v1alpha.cardano.TxOutputPatternH\x00R\acardanoB\x0e\n" +
	"\futxo_pattern\"\xfe\x01\n" +
	"\rUtxoPredicate\x12;\n" +
	"\x05match\x18\x01 \x01(\v2%.utxorpc.v1alpha.query.AnyUtxoPatternR\x05match\x126\n" +
	"\x03not\x18\x02 \x03(\v2$.utxorpc.v1alpha.query.UtxoPredicateR\x03not\x12;\n" +
	"\x06all_of\x18\x03 \x03(\v2$.utxorpc.v1alpha.query.UtxoPredicateR\x05allOf\x12;\n" +
	"\x06any_of\x18\x04 \x03(\v2$.utxorpc.v1alpha.query.UtxoPredicateR\x05anyOf\"\xf7\x01\n" +
	"\vAnyUtxoData\x12!\n" +
	"\fnative_bytes\x18\x01 \x01(\fR\vnativeBytes\x126\n" +
	"\atxo_ref\x18\x02 \x01(\v2\x1d.utxorpc.v1alpha.query.TxoRefR\x06txoRef\x12=\n" +
	"\acardano\x18\x03 \x01(\v2!.utxorpc.v1alpha.cardano.TxOutputH\x00R\acardano\x12>\n" +
	"\tblock_ref\x18\x04 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\bblockRefB\x0e\n" +
	"\fparsed_state\"\x80\x01\n" +
	"\x10ReadUtxosRequest\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.utxorpc.v1alpha.query.TxoRefR\x04keys\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x8f\x01\n" +
	"\x11ReadUtxosResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".utxorpc.v1alpha.query.AnyUtxoDataR\x05items\x12@\n" +
	"\n" +
	"ledger_tip\x18\x02 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\tledgerTip\"\xd1\x01\n" +
	"\x12SearchUtxosRequest\x12B\n" +
	"\tpredicate\x18\x01 \x01(\v2$.utxorpc.v1alpha.query.UtxoPredicateR\tpredicate\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\x05R\bmaxItems\x12\x1f\n" +
	"\vstart_token\x18\x04 \x01(\tR\n" +
	"startToken\"\xb0\x01\n" +
	"\x13SearchUtxosResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".utxorpc.v1alpha.query.AnyUtxoDataR\x05items\x12@\n" +
	"\n" +
	"ledger_tip\x18\x02 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\tledgerTip\x12\x1d\n" +
	"\n" +
	"next_token\x18\x03 \x01(\tR\tnextToken\"`\n" +
	"\x0fReadDataRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\fR\x04keys\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x95\x01\n" +
	"\rAnyChainDatum\x12!\n" +
	"\fnative_bytes\x18\x01 \x01(\fR\vnativeBytes\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12?\n" +
	"\acardano\x18\x03 \x01(\v2#.utxorpc.v1alpha.cardano.PlutusDataH\x00R\acardanoB\x0e\n" +
	"\fparsed_state\"\x92\x01\n" +
	"\x10ReadDataResponse\x12<\n" +
	"\x06values\x18\x01 \x03(\v2$.utxorpc.v1alpha.query.AnyChainDatumR\x06values\x12@\n" +
	"\n" +
	"ledger_tip\x18\x02 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\tledgerTip\"^\n" +
	"\rReadTxRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\xb1\x01\n" +
	"\n" +
	"AnyChainTx\x12!\n" +
	"\fnative_bytes\x18\x01 \x01(\fR\vnativeBytes\x127\n" +
	"\acardano\x18\x02 \x01(\v2\x1b.utxorpc.v1alpha.cardano.TxH\x00R\acardano\x12>\n" +
	"\tblock_ref\x18\x03 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\bblockRefB\a\n" +
	"\x05chain\"\x85\x01\n" +
	"\x0eReadTxResponse\x121\n" +
	"\x02tx\x18\x01 \x01(\v2!.utxorpc.v1alpha.query.AnyChainTxR\x02tx\x12@\n" +
	"\n" +
	"ledger_tip\x18\x02 \x01(\v2!.utxorpc.v1alpha.query.ChainPointR\tledgerTip2\xc0\x05\n" +
	"\fQueryService\x12a\n" +
	"\n" +
	"ReadParams\x12(.utxorpc.v1alpha.query.ReadParamsRequest\x1a).utxorpc.v1alpha.query.ReadParamsResponse\x12^\n" +
	"\tReadUtxos\x12'.utxorpc.v1alpha.query.ReadUtxosRequest\x1a(.utxorpc.v1alpha.query.ReadUtxosResponse\x12d\n" +
	"\vSearchUtxos\x12).utxorpc.v1alpha.query.SearchUtxosRequest\x1a*.utxorpc.v1alpha.query.SearchUtxosResponse\x12[\n" +
	"\bReadData\x12&.utxorpc.v1alpha.query.ReadDataRequest\x1a'.utxorpc.v1alpha.query.ReadDataResponse\x12U\n" +
	"\x06ReadTx\x12$.utxorpc.v1alpha.query.ReadTxRequest\x1a%.utxorpc.v1alpha.query.ReadTxResponse\x12d\n" +
	"\vReadGenesis\x12).utxorpc.v1alpha.query.ReadGenesisRequest\x1a*.utxorpc.v1alpha.query.ReadGenesisResponse\x12m\n" +
	"\x0eReadEraSummary\x12,.utxorpc.v1alpha.query.ReadEraSummaryRequest\x1a-.utxorpc.v1alpha.query.ReadEraSummaryResponseB\xd2\x01\n" +
	"\x19com.utxorpc.v1alpha.queryB\n" +
	"QueryProtoP\x01Z3github.com/utxorpc/go-codegen/utxorpc/v1alpha/query\xa2\x02\x03UVQ\xaa\x02\x15Utxorpc.V1alpha.Query\xca\x02\x15Utxorpc\\V1alpha\\Query\xe2\x02!Utxorpc\\V1alpha\\Query\\GPBMetadata\xea\x02\x17Utxorpc::V1alpha::Queryb\x06proto3"

var (
	file_utxorpc_v1alpha_query_query_proto_rawDescOnce sync.Once
	file_utxorpc_v1alpha_query_query_proto_rawDescData []byte
)

func file_utxorpc_v1alpha_query_query_proto_rawDescGZIP() []byte {
	file_utxorpc_v1alpha_query_query_proto_rawDescOnce.Do(func() {
		file_utxorpc_v1alpha_query_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utxorpc_v1alpha_query_query_proto_rawDesc), len(file_utxorpc_v1alpha_query_query_proto_rawDesc)))
	})
	return file_utxorpc_v1alpha_query_query_proto_rawDescData
}

var file_utxorpc_v1alpha_query_query_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_utxorpc_v1alpha_query_query_proto_goTypes = []any{
	(*ChainPoint)(nil),              // 0: utxorpc.v1alpha.query.ChainPoint
	(*AnyChainBlock)(nil),           // 1: utxorpc.v1alpha.query.AnyChainBlock
	(*TxoRef)(nil),                  // 2: utxorpc.v1alpha.query.TxoRef
	(*ReadParamsRequest)(nil),       // 3: utxorpc.v1alpha.query.ReadParamsRequest
	(*ReadGenesisRequest)(nil),      // 4: utxorpc.v1alpha.query.ReadGenesisRequest
	(*ReadEraSummaryRequest)(nil),   // 5: utxorpc.v1alpha.query.ReadEraSummaryRequest
	(*ReadGenesisResponse)(nil),     // 6: utxorpc.v1alpha.query.ReadGenesisResponse
	(*ReadEraSummaryResponse)(nil),  // 7: utxorpc.v1alpha.query.ReadEraSummaryResponse
	(*AnyChainParams)(nil),          // 8: utxorpc.v1alpha.query.AnyChainParams
	(*ReadParamsResponse)(nil),      // 9: utxorpc.v1alpha.query.ReadParamsResponse
	(*AnyUtxoPattern)(nil),          // 10: utxorpc.v1alpha.query.AnyUtxoPattern
	(*UtxoPredicate)(nil),           // 11: utxorpc.v1alpha.query.UtxoPredicate
	(*AnyUtxoData)(nil),             // 12: utxorpc.v1alpha.query.AnyUtxoData
	(*ReadUtxosRequest)(nil),        // 13: utxorpc.v1alpha.query.ReadUtxosRequest
	(*ReadUtxosResponse)(nil),       // 14: utxorpc.v1alpha.query.ReadUtxosResponse
	(*SearchUtxosRequest)(nil),      // 15: utxorpc.v1alpha.query.SearchUtxosRequest
	(*SearchUtxosResponse)(nil),     // 16: utxorpc.v1alpha.query.SearchUtxosResponse
	(*ReadDataRequest)(nil),         // 17: utxorpc.v1alpha.query.ReadDataRequest
	(*AnyChainDatum)(nil),           // 18: utxorpc.v1alpha.query.AnyChainDatum
	(*ReadDataResponse)(nil),        // 19: utxorpc.v1alpha.query.ReadDataResponse
	(*ReadTxRequest)(nil),           // 20: utxorpc.v1alpha.query.ReadTxRequest
	(*AnyChainTx)(nil),              // 21: utxorpc.v1alpha.query.AnyChainTx
	(*ReadTxResponse)(nil),          // 22: utxorpc.v1alpha.query.ReadTxResponse
	(*cardano.Block)(nil),           // 23: utxorpc.v1alpha.cardano.Block
	(*fieldmaskpb.FieldMask)(nil),   // 24: google.protobuf.FieldMask
	(*cardano.Genesis)(nil),         // 25: utxorpc.v1alpha.cardano.Genesis
	(*cardano.EraSummaries)(nil),    // 26: utxorpc.v1alpha.cardano.EraSummaries
	(*cardano.PParams)(nil),         // 27: utxorpc.v1alpha.cardano.PParams
	(*cardano.TxOutputPattern)(nil), // 28: utxorpc.v1alpha.cardano.TxOutputPattern
	(*cardano.TxOutput)(nil),        // 29: utxorpc.v1alpha.cardano.TxOutput
	(*cardano.PlutusData)(nil),      // 30: utxorpc.v1alpha.cardano.PlutusData
	(*cardano.Tx)(nil),              // 31: utxorpc.v1alpha.cardano.Tx
}
var file_utxorpc_v1alpha_query_query_proto_depIdxs = []int32{
	23, // 0: utxorpc.v1alpha.query.AnyChainBlock.cardano:type_name -> utxorpc.v1alpha.cardano.Block
	24, // 1: utxorpc.v1alpha.query.ReadParamsRequest.field_mask:type_name -> google.protobuf.FieldMask
	24, // 2: utxorpc.v1alpha.query.ReadGenesisRequest.field_mask:type_name -> google.protobuf.FieldMask
	24, // 3: utxorpc.v1alpha.query.ReadEraSummaryRequest.field_mask:type_name -> google.protobuf.FieldMask
	25, // 4: utxorpc.v1alpha.query.ReadGenesisResponse.cardano:type_name -> utxorpc.v1alpha.cardano.Genesis
	26, // 5: utxorpc.v1alpha.query.ReadEraSummaryResponse.cardano:type_name -> utxorpc.v1alpha.cardano.EraSummaries
	27, // 6: utxorpc.v1alpha.query.AnyChainParams.cardano:type_name -> utxorpc.v1alpha.cardano.PParams
	8,  // 7: utxorpc.v1alpha.query.ReadParamsResponse.values:type_name -> utxorpc.v1alpha.query.AnyChainParams
	0,  // 8: utxorpc.v1alpha.query.ReadParamsResponse.ledger_tip:type_name -> utxorpc.v1alpha.query.ChainPoint
	28, // 9: utxorpc.v1alpha.query.AnyUtxoPattern.cardano:type_name -> utxorpc.v1alpha.cardano.TxOutputPattern
	10, // 10: utxorpc.v1alpha.query.UtxoPredicate.match:type_name -> utxorpc.v1alpha.query.AnyUtxoPattern
	11, // 11: utxorpc.v1alpha.query.UtxoPredicate.not:type_name -> utxorpc.v1alpha.query.UtxoPredicate
	11, // 12: utxorpc.v1alpha.query.UtxoPredicate.all_of:type_name -> utxorpc.v1alpha.query.UtxoPredicate
	11, // 13: utxorpc.v1alpha.query.UtxoPredicate.any_of:type_name -> utxorpc.v1alpha.query.UtxoPredicate
	2,  // 14: utxorpc.v1alpha.query.AnyUtxoData.txo_ref:type_name -> utxorpc.v1alpha.query.TxoRef
	29, // 15: utxorpc.v1alpha.query.AnyUtxoData.cardano:type_name -> utxorpc.v1alpha.cardano.TxOutput
	0,  // 16: utxorpc.v1alpha.query.AnyUtxoData.block_ref:type_name -> utxorpc.v1alpha.query.ChainPoint
	2,  // 17: utxorpc.v1alpha.query.ReadUtxosRequest.keys:type_name -> utxorpc.v1alpha.query.TxoRef
	24, // 18: utxorpc.v1alpha.query.ReadUtxosRequest.field_mask:type_name -> google.protobuf.FieldMask
	12, // 19: utxorpc.v1alpha.query.ReadUtxosResponse.items:type_name -> utxorpc.v1alpha.query.AnyUtxoData
	0,  // 20: utxorpc.v1alpha.query.ReadUtxosResponse.ledger_tip:type_name -> utxorpc.v1alpha.query.ChainPoint
	11, // 21: utxorpc.v1alpha.query.SearchUtxosRequest.predicate:type_name -> utxorpc.v1alpha.query.UtxoPredicate
	24, // 22: utxorpc.v1alpha.query.SearchUtxosRequest.field_mask:type_name -> google.protobuf.FieldMask
	12, // 23: utxorpc.v1alpha.query.SearchUtxosResponse.items:type_name -> utxorpc.v1alpha.query.AnyUtxoData
	0,  // 24: utxorpc.v1alpha.query.SearchUtxosResponse.ledger_tip:type_name -> utxorpc.v1alpha.query.ChainPoint
	24, // 25: utxorpc.v1alpha.query.ReadDataRequest.field_mask:type_name -> google.protobuf.FieldMask
	30, // 26: utxorpc.v1alpha.query.AnyChainDatum.cardano:type_name -> utxorpc.v1alpha.cardano.PlutusData
	18, // 27: utxorpc.v1alpha.query.ReadDataResponse.values:type_name -> utxorpc.v1alpha.query.AnyChainDatum
	0,  // 28: utxorpc.v1alpha.query.ReadDataResponse.ledger_tip:type_name -> utxorpc.v1alpha.query.ChainPoint
	24, // 29: utxorpc.v1alpha.query.ReadTxRequest.field_mask:type_name -> google.protobuf.FieldMask
	31, // 30: utxorpc.v1alpha.query.AnyChainTx.cardano:type_name -> utxorpc.v1alpha.cardano.Tx
	0,  // 31: utxorpc.v1alpha.query.AnyChainTx.block_ref:type_name -> utxorpc.v1alpha.query.ChainPoint
	21, // 32: utxorpc.v1alpha.query.ReadTxResponse.tx:type_name -> utxorpc.v1alpha.query.AnyChainTx
	0,  // 33: utxorpc.v1alpha.query.ReadTxResponse.ledger_tip:type_name -> utxorpc.v1alpha.query.ChainPoint
	3,  // 34: utxorpc.v1alpha.query.QueryService.ReadParams:input_type -> utxorpc.v1alpha.query.ReadParamsRequest
	13, // 35: utxorpc.v1alpha.query.QueryService.ReadUtxos:input_type -> utxorpc.v1alpha.query.ReadUtxosRequest
	15, // 36: utxorpc.v1alpha.query.QueryService.SearchUtxos:input_type -> utxorpc.v1alpha.query.SearchUtxosRequest
	17, // 37: utxorpc.v1alpha.query.QueryService.ReadData:input_type -> utxorpc.v1alpha.query.ReadDataRequest
	20, // 38: utxorpc.v1alpha.query.QueryService.ReadTx:input_type -> utxorpc.v1alpha.query.ReadTxRequest
	4,  // 39: utxorpc.v1alpha.query.QueryService.ReadGenesis:input_type -> utxorpc.v1alpha.query.ReadGenesisRequest
	5,  // 40: utxorpc.v1alpha.query.QueryService.ReadEraSummary:input_type -> utxorpc.v1alpha.query.ReadEraSummaryRequest
	9,  // 41: utxorpc.v1alpha.query.QueryService.ReadParams:output_type -> utxorpc.v1alpha.query.ReadParamsResponse
	14, // 42: utxorpc.v1alpha.query.QueryService.ReadUtxos:output_type -> utxorpc.v1alpha.query.ReadUtxosResponse
	16, // 43: utxorpc.v1alpha.query.QueryService.SearchUtxos:output_type -> utxorpc.v1alpha.query.SearchUtxosResponse
	19, // 44: utxorpc.v1alpha.query.QueryService.ReadData:output_type -> utxorpc.v1alpha.query.ReadDataResponse
	22, // 45: utxorpc.v1alpha.query.QueryService.ReadTx:output_type -> utxorpc.v1alpha.query.ReadTxResponse
	6,  // 46: utxorpc.v1alpha.query.QueryService.ReadGenesis:output_type -> utxorpc.v1alpha.query.ReadGenesisResponse
	7,  // 47: utxorpc.v1alpha.query.QueryService.ReadEraSummary:output_type -> utxorpc.v1alpha.query.ReadEraSummaryResponse
	41, // [41:48] is the sub-list for method output_type
	34, // [34:41] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_utxorpc_v1alpha_query_query_proto_init() }
func file_utxorpc_v1alpha_query_query_proto_init() {
	if File_utxorpc_v1alpha_query_query_proto != nil {
		return
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[1].OneofWrappers = []any{
		(*AnyChainBlock_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[6].OneofWrappers = []any{
		(*ReadGenesisResponse_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[7].OneofWrappers = []any{
		(*ReadEraSummaryResponse_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[8].OneofWrappers = []any{
		(*AnyChainParams_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[10].OneofWrappers = []any{
		(*AnyUtxoPattern_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[12].OneofWrappers = []any{
		(*AnyUtxoData_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[18].OneofWrappers = []any{
		(*AnyChainDatum_Cardano)(nil),
	}
	file_utxorpc_v1alpha_query_query_proto_msgTypes[21].OneofWrappers = []any{
		(*AnyChainTx_Cardano)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utxorpc_v1alpha_query_query_proto_rawDesc), len(file_utxorpc_v1alpha_query_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utxorpc_v1alpha_query_query_proto_goTypes,
		DependencyIndexes: file_utxorpc_v1alpha_query_query_proto_depIdxs,
		MessageInfos:      file_utxorpc_v1alpha_query_query_proto_msgTypes,
	}.Build()
	File_utxorpc_v1alpha_query_query_proto = out.File
	file_utxorpc_v1alpha_query_query_proto_goTypes = nil
	file_utxorpc_v1alpha_query_query_proto_depIdxs = nil
}
