// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: utxorpc/v1beta/handshake/handshake.proto

package handshake

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Covenant action types for the Handshake naming system.
type CovenantAction int32

const (
	CovenantAction_COVENANT_ACTION_UNSPECIFIED CovenantAction = 0  // No covenant (regular transfer)
	CovenantAction_COVENANT_ACTION_CLAIM       CovenantAction = 1  // Claim a reserved legacy DNS name
	CovenantAction_COVENANT_ACTION_OPEN        CovenantAction = 2  // Open a name auction
	CovenantAction_COVENANT_ACTION_BID         CovenantAction = 3  // Submit a blinded bid
	CovenantAction_COVENANT_ACTION_REVEAL      CovenantAction = 4  // Reveal a bid amount
	CovenantAction_COVENANT_ACTION_REDEEM      CovenantAction = 5  // Recover a losing bid
	CovenantAction_COVENANT_ACTION_REGISTER    CovenantAction = 6  // Finalize name ownership after winning auction
	CovenantAction_COVENANT_ACTION_UPDATE      CovenantAction = 7  // Update DNS resource data for a name
	CovenantAction_COVENANT_ACTION_RENEW       CovenantAction = 8  // Renew name ownership
	CovenantAction_COVENANT_ACTION_TRANSFER    CovenantAction = 9  // Initiate ownership transfer
	CovenantAction_COVENANT_ACTION_FINALIZE    CovenantAction = 10 // Confirm ownership transfer
	CovenantAction_COVENANT_ACTION_REVOKE      CovenantAction = 11 // Revoke a name permanently
)

// Enum value maps for CovenantAction.
var (
	CovenantAction_name = map[int32]string{
		0:  "COVENANT_ACTION_UNSPECIFIED",
		1:  "COVENANT_ACTION_CLAIM",
		2:  "COVENANT_ACTION_OPEN",
		3:  "COVENANT_ACTION_BID",
		4:  "COVENANT_ACTION_REVEAL",
		5:  "COVENANT_ACTION_REDEEM",
		6:  "COVENANT_ACTION_REGISTER",
		7:  "COVENANT_ACTION_UPDATE",
		8:  "COVENANT_ACTION_RENEW",
		9:  "COVENANT_ACTION_TRANSFER",
		10: "COVENANT_ACTION_FINALIZE",
		11: "COVENANT_ACTION_REVOKE",
	}
	CovenantAction_value = map[string]int32{
		"COVENANT_ACTION_UNSPECIFIED": 0,
		"COVENANT_ACTION_CLAIM":       1,
		"COVENANT_ACTION_OPEN":        2,
		"COVENANT_ACTION_BID":         3,
		"COVENANT_ACTION_REVEAL":      4,
		"COVENANT_ACTION_REDEEM":      5,
		"COVENANT_ACTION_REGISTER":    6,
		"COVENANT_ACTION_UPDATE":      7,
		"COVENANT_ACTION_RENEW":       8,
		"COVENANT_ACTION_TRANSFER":    9,
		"COVENANT_ACTION_FINALIZE":    10,
		"COVENANT_ACTION_REVOKE":      11,
	}
)

func (x CovenantAction) Enum() *CovenantAction {
	p := new(CovenantAction)
	*p = x
	return p
}

func (x CovenantAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CovenantAction) Descriptor() protoreflect.EnumDescriptor {
	return file_utxorpc_v1beta_handshake_handshake_proto_enumTypes[0].Descriptor()
}

func (CovenantAction) Type() protoreflect.EnumType {
	return &file_utxorpc_v1beta_handshake_handshake_proto_enumTypes[0]
}

func (x CovenantAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CovenantAction.Descriptor instead.
func (CovenantAction) EnumDescriptor() ([]byte, []int) {
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP(), []int{0}
}

// Represents a covenant attached to a transaction output.
type Covenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        CovenantAction         `protobuf:"varint,1,opt,name=action,proto3,enum=utxorpc.v1beta.handshake.CovenantAction" json:"action,omitempty"` // The covenant action type
	Items         [][]byte               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                                                 // Covenant data items (name hash, resource data, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Covenant) Reset() {
	*x = Covenant{}
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Covenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Covenant) ProtoMessage() {}

func (x *Covenant) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Covenant.ProtoReflect.Descriptor instead.
func (*Covenant) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *Covenant) GetAction() CovenantAction {
	if x != nil {
		return x.Action
	}
	return CovenantAction_COVENANT_ACTION_UNSPECIFIED
}

func (x *Covenant) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// Represents an input in a Handshake transaction.
type TxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3,oneof" json:"txid,omitempty"`                             // Hash of the previous transaction being spent
	OutputIndex   uint32                 `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"` // Index of the output in the previous transaction
	Sequence      uint32                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`                          // Sequence number, used for relative timelocks
	Witness       [][]byte               `protobuf:"bytes,4,rep,name=witness,proto3" json:"witness,omitempty"`                             // Witness stack items (Handshake is SegWit-only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInput) Reset() {
	*x = TxInput{}
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInput) ProtoMessage() {}

func (x *TxInput) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInput.ProtoReflect.Descriptor instead.
func (*TxInput) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *TxInput) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *TxInput) GetOutputIndex() uint32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *TxInput) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TxInput) GetWitness() [][]byte {
	if x != nil {
		return x.Witness
	}
	return nil
}

// Represents an output in a Handshake transaction.
type TxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`      // Amount in dollarydoos (smallest HNS unit, 1 HNS = 1,000,000 dollarydoos)
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`   // Witness program address
	Covenant      *Covenant              `protobuf:"bytes,3,opt,name=covenant,proto3" json:"covenant,omitempty"` // Covenant restricting future use of this output
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutput) Reset() {
	*x = TxOutput{}
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutput) ProtoMessage() {}

func (x *TxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutput.ProtoReflect.Descriptor instead.
func (*TxOutput) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *TxOutput) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutput) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TxOutput) GetCovenant() *Covenant {
	if x != nil {
		return x.Covenant
	}
	return nil
}

// Represents a transaction in the Handshake network.
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                 // Transaction version number
	Vin           []*TxInput             `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`                                          // List of transaction inputs
	Vout          []*TxOutput            `protobuf:"bytes,3,rep,name=vout,proto3" json:"vout,omitempty"`                                        // List of transaction outputs
	Locktime      uint32                 `protobuf:"varint,4,opt,name=locktime,proto3" json:"locktime,omitempty"`                               // Block height or timestamp when transaction is final
	Hash          []byte                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`                                        // Hash of the transaction
	WitnessHash   []byte                 `protobuf:"bytes,6,opt,name=witness_hash,json=witnessHash,proto3,oneof" json:"witness_hash,omitempty"` // Witness-committed hash
	Blockhash     []byte                 `protobuf:"bytes,7,opt,name=blockhash,proto3,oneof" json:"blockhash,omitempty"`                        // Hash of the containing block
	Time          *uint32                `protobuf:"varint,8,opt,name=time,proto3,oneof" json:"time,omitempty"`                                 // Timestamp of the transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Transaction) GetVin() []*TxInput {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *Transaction) GetVout() []*TxOutput {
	if x != nil {
		return x.Vout
	}
	return nil
}

func (x *Transaction) GetLocktime() uint32 {
	if x != nil {
		return x.Locktime
	}
	return 0
}

func (x *Transaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Transaction) GetWitnessHash() []byte {
	if x != nil {
		return x.WitnessHash
	}
	return nil
}

func (x *Transaction) GetBlockhash() []byte {
	if x != nil {
		return x.Blockhash
	}
	return nil
}

func (x *Transaction) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

// Represents a block in the Handshake blockchain.
type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                                   // Block version number
	PreviousBlockhash []byte                 `protobuf:"bytes,2,opt,name=previous_blockhash,json=previousBlockhash,proto3,oneof" json:"previous_blockhash,omitempty"` // Hash of the previous block
	MerkleRoot        []byte                 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`                            // Merkle root of base transaction data
	WitnessRoot       []byte                 `protobuf:"bytes,4,opt,name=witness_root,json=witnessRoot,proto3" json:"witness_root,omitempty"`                         // Merkle root of transaction witness data
	TreeRoot          []byte                 `protobuf:"bytes,5,opt,name=tree_root,json=treeRoot,proto3" json:"tree_root,omitempty"`                                  // Root of the name-resource urkel tree
	ReservedRoot      []byte                 `protobuf:"bytes,6,opt,name=reserved_root,json=reservedRoot,proto3" json:"reserved_root,omitempty"`                      // Reserved root for future layer 2 expansion
	Time              uint32                 `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`                                                         // Time when the block was created
	Bits              uint32                 `protobuf:"varint,8,opt,name=bits,proto3" json:"bits,omitempty"`                                                         // Target difficulty value
	Nonce             []byte                 `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                        // Nonce used for Proof-of-Work
	ExtraNonce        []byte                 `protobuf:"bytes,10,opt,name=extra_nonce,json=extraNonce,proto3" json:"extra_nonce,omitempty"`                           // Extra nonce for expanded mining search space
	Mask              []byte                 `protobuf:"bytes,11,opt,name=mask,proto3" json:"mask,omitempty"`                                                         // Mask for committed block hash
	Tx                []*Transaction         `protobuf:"bytes,12,rep,name=tx,proto3" json:"tx,omitempty"`                                                             // List of transactions included in the block
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *Block) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Block) GetPreviousBlockhash() []byte {
	if x != nil {
		return x.PreviousBlockhash
	}
	return nil
}

func (x *Block) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *Block) GetWitnessRoot() []byte {
	if x != nil {
		return x.WitnessRoot
	}
	return nil
}

func (x *Block) GetTreeRoot() []byte {
	if x != nil {
		return x.TreeRoot
	}
	return nil
}

func (x *Block) GetReservedRoot() []byte {
	if x != nil {
		return x.ReservedRoot
	}
	return nil
}

func (x *Block) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Block) GetBits() uint32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *Block) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Block) GetExtraNonce() []byte {
	if x != nil {
		return x.ExtraNonce
	}
	return nil
}

func (x *Block) GetMask() []byte {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *Block) GetTx() []*Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

var File_utxorpc_v1beta_handshake_handshake_proto protoreflect.FileDescriptor

const file_utxorpc_v1beta_handshake_handshake_proto_rawDesc = "" +
	"\n" +
	"(utxorpc/v1beta/handshake/handshake.proto\x12\x18utxorpc.v1beta.handshake\"b\n" +
	"\bCovenant\x12@\n" +
	"\x06action\x18\x01 \x01(\x0e2(.utxorpc.v1beta.handshake.CovenantActionR\x06action\x12\x14\n" +
	"\x05items\x18\x02 \x03(\fR\x05items\"\x84\x01\n" +
	"\aTxInput\x12\x17\n" +
	"\x04txid\x18\x01 \x01(\fH\x00R\x04txid\x88\x01\x01\x12!\n" +
	"\foutput_index\x18\x02 \x01(\rR\voutputIndex\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12\x18\n" +
	"\awitness\x18\x04 \x03(\fR\awitnessB\a\n" +
	"\x05_txid\"z\n" +
	"\bTxOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12>\n" +
	"\bcovenant\x18\x03 \x01(\v2\".utxorpc.v1beta.handshake.CovenantR\bcovenant\"\xd0\x02\n" +
	"\vTransaction\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x123\n" +
	"\x03vin\x18\x02 \x03(\v2!.utxorpc.v1beta.handshake.TxInputR\x03vin\x126\n" +
	"\x04vout\x18\x03 \x03(\v2\".utxorpc.v1beta.handshake.TxOutputR\x04vout\x12\x1a\n" +
	"\blocktime\x18\x04 \x01(\rR\blocktime\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\fR\x04hash\x12&\n" +
	"\fwitness_hash\x18\x06 \x01(\fH\x00R\vwitnessHash\x88\x01\x01\x12!\n" +
	"\tblockhash\x18\a \x01(\fH\x01R\tblockhash\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\b \x01(\rH\x02R\x04time\x88\x01\x01B\x0f\n" +
	"\r_witness_hashB\f\n" +
	"\n" +
	"_blockhashB\a\n" +
	"\x05_time\"\x9c\x03\n" +
	"\x05Block\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x122\n" +
	"\x12previous_blockhash\x18\x02 \x01(\fH\x00R\x11previousBlockhash\x88\x01\x01\x12\x1f\n" +
	"\vmerkle_root\x18\x03 \x01(\fR\n" +
	"merkleRoot\x12!\n" +
	"\fwitness_root\x18\x04 \x01(\fR\vwitnessRoot\x12\x1b\n" +
	"\ttree_root\x18\x05 \x01(\fR\btreeRoot\x12#\n" +
	"\rreserved_root\x18\x06 \x01(\fR\freservedRoot\x12\x12\n" +
	"\x04time\x18\a \x01(\rR\x04time\x12\x12\n" +
	"\x04bits\x18\b \x01(\rR\x04bits\x12\x14\n" +
	"\x05nonce\x18\t \x01(\fR\x05nonce\x12\x1f\n" +
	"\vextra_nonce\x18\n" +
	" \x01(\fR\n" +
	"extraNonce\x12\x12\n" +
	"\x04mask\x18\v \x01(\fR\x04mask\x125\n" +
	"\x02tx\x18\f \x03(\v2%.utxorpc.v1beta.handshake.TransactionR\x02txB\x15\n" +
	"\x13_previous_blockhash*\xe4\x02\n" +
	"\x0eCovenantAction\x12\x1f\n" +
	"\x1bCOVENANT_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COVENANT_ACTION_CLAIM\x10\x01\x12\x18\n" +
	"\x14COVENANT_ACTION_OPEN\x10\x02\x12\x17\n" +
	"\x13COVENANT_ACTION_BID\x10\x03\x12\x1a\n" +
	"\x16COVENANT_ACTION_REVEAL\x10\x04\x12\x1a\n" +
	"\x16COVENANT_ACTION_REDEEM\x10\x05\x12\x1c\n" +
	"\x18COVENANT_ACTION_REGISTER\x10\x06\x12\x1a\n" +
	"\x16COVENANT_ACTION_UPDATE\x10\a\x12\x19\n" +
	"\x15COVENANT_ACTION_RENEW\x10\b\x12\x1c\n" +
	"\x18COVENANT_ACTION_TRANSFER\x10\t\x12\x1c\n" +
	"\x18COVENANT_ACTION_FINALIZE\x10\n" +
	"\x12\x1a\n" +
	"\x16COVENANT_ACTION_REVOKE\x10\vB\xe8\x01\n" +
	"\x1ccom.utxorpc.v1beta.handshakeB\x0eHandshakeProtoP\x01Z6github.com/utxorpc/go-codegen/utxorpc/v1beta/handshake\xa2\x02\x03UVH\xaa\x02\x18Utxorpc.V1beta.Handshake\xca\x02\x18Utxorpc\\V1beta\\Handshake\xe2\x02$Utxorpc\\V1beta\\Handshake\\GPBMetadata\xea\x02\x1aUtxorpc::V1beta::Handshakeb\x06proto3"

var (
	file_utxorpc_v1beta_handshake_handshake_proto_rawDescOnce sync.Once
	file_utxorpc_v1beta_handshake_handshake_proto_rawDescData []byte
)

func file_utxorpc_v1beta_handshake_handshake_proto_rawDescGZIP() []byte {
	file_utxorpc_v1beta_handshake_handshake_proto_rawDescOnce.Do(func() {
		file_utxorpc_v1beta_handshake_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utxorpc_v1beta_handshake_handshake_proto_rawDesc), len(file_utxorpc_v1beta_handshake_handshake_proto_rawDesc)))
	})
	return file_utxorpc_v1beta_handshake_handshake_proto_rawDescData
}

var file_utxorpc_v1beta_handshake_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_utxorpc_v1beta_handshake_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_utxorpc_v1beta_handshake_handshake_proto_goTypes = []any{
	(CovenantAction)(0), // 0: utxorpc.v1beta.handshake.CovenantAction
	(*Covenant)(nil),    // 1: utxorpc.v1beta.handshake.Covenant
	(*TxInput)(nil),     // 2: utxorpc.v1beta.handshake.TxInput
	(*TxOutput)(nil),    // 3: utxorpc.v1beta.handshake.TxOutput
	(*Transaction)(nil), // 4: utxorpc.v1beta.handshake.Transaction
	(*Block)(nil),       // 5: utxorpc.v1beta.handshake.Block
}
var file_utxorpc_v1beta_handshake_handshake_proto_depIdxs = []int32{
	0, // 0: utxorpc.v1beta.handshake.Covenant.action:type_name -> utxorpc.v1beta.handshake.CovenantAction
	1, // 1: utxorpc.v1beta.handshake.TxOutput.covenant:type_name -> utxorpc.v1beta.handshake.Covenant
	2, // 2: utxorpc.v1beta.handshake.Transaction.vin:type_name -> utxorpc.v1beta.handshake.TxInput
	3, // 3: utxorpc.v1beta.handshake.Transaction.vout:type_name -> utxorpc.v1beta.handshake.TxOutput
	4, // 4: utxorpc.v1beta.handshake.Block.tx:type_name -> utxorpc.v1beta.handshake.Transaction
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_utxorpc_v1beta_handshake_handshake_proto_init() }
func file_utxorpc_v1beta_handshake_handshake_proto_init() {
	if File_utxorpc_v1beta_handshake_handshake_proto != nil {
		return
	}
	file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[1].OneofWrappers = []any{}
	file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[3].OneofWrappers = []any{}
	file_utxorpc_v1beta_handshake_handshake_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utxorpc_v1beta_handshake_handshake_proto_rawDesc), len(file_utxorpc_v1beta_handshake_handshake_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utxorpc_v1beta_handshake_handshake_proto_goTypes,
		DependencyIndexes: file_utxorpc_v1beta_handshake_handshake_proto_depIdxs,
		EnumInfos:         file_utxorpc_v1beta_handshake_handshake_proto_enumTypes,
		MessageInfos:      file_utxorpc_v1beta_handshake_handshake_proto_msgTypes,
	}.Build()
	File_utxorpc_v1beta_handshake_handshake_proto = out.File
	file_utxorpc_v1beta_handshake_handshake_proto_goTypes = nil
	file_utxorpc_v1beta_handshake_handshake_proto_depIdxs = nil
}
