// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: utxorpc/v1alpha/sync/sync.proto

package sync

import (
	cardano "github.com/utxorpc/go-codegen/utxorpc/v1alpha/cardano"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a reference to a specific block by a chosen combination of fields
type BlockRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`           // Height or slot number (depending on the blockchain)
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`            // Hash of the content of the block
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`       // Block height
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Block ms timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRef) Reset() {
	*x = BlockRef{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRef) ProtoMessage() {}

func (x *BlockRef) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRef.ProtoReflect.Descriptor instead.
func (*BlockRef) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRef) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BlockRef) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockRef) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockRef) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AnyChainBlock struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NativeBytes []byte                 `protobuf:"bytes,1,opt,name=native_bytes,json=nativeBytes,proto3" json:"native_bytes,omitempty"` // Original bytes as defined by the chain
	// Types that are valid to be assigned to Chain:
	//
	//	*AnyChainBlock_Cardano
	Chain         isAnyChainBlock_Chain `protobuf_oneof:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainBlock) Reset() {
	*x = AnyChainBlock{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainBlock) ProtoMessage() {}

func (x *AnyChainBlock) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainBlock.ProtoReflect.Descriptor instead.
func (*AnyChainBlock) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *AnyChainBlock) GetNativeBytes() []byte {
	if x != nil {
		return x.NativeBytes
	}
	return nil
}

func (x *AnyChainBlock) GetChain() isAnyChainBlock_Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *AnyChainBlock) GetCardano() *cardano.Block {
	if x != nil {
		if x, ok := x.Chain.(*AnyChainBlock_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyChainBlock_Chain interface {
	isAnyChainBlock_Chain()
}

type AnyChainBlock_Cardano struct {
	Cardano *cardano.Block `protobuf:"bytes,2,opt,name=cardano,proto3,oneof"` // A parsed Cardano block.
}

func (*AnyChainBlock_Cardano) isAnyChainBlock_Chain() {}

// Request to fetch a block by its reference.
type FetchBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           []*BlockRef            `protobuf:"bytes,1,rep,name=ref,proto3" json:"ref,omitempty"`                              // List of block references.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlockRequest) Reset() {
	*x = FetchBlockRequest{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlockRequest) ProtoMessage() {}

func (x *FetchBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlockRequest.ProtoReflect.Descriptor instead.
func (*FetchBlockRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *FetchBlockRequest) GetRef() []*BlockRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *FetchBlockRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response containing the fetched blocks.
type FetchBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []*AnyChainBlock       `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"` // List of fetched blocks.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBlockResponse) Reset() {
	*x = FetchBlockResponse{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlockResponse) ProtoMessage() {}

func (x *FetchBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlockResponse.ProtoReflect.Descriptor instead.
func (*FetchBlockResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *FetchBlockResponse) GetBlock() []*AnyChainBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

// Request to dump the block history.
type DumpHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartToken    *BlockRef              `protobuf:"bytes,2,opt,name=start_token,json=startToken,proto3" json:"start_token,omitempty"` // Starting point for the block history dump.
	MaxItems      uint32                 `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`      // Maximum number of items to return.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`    // Field mask to selectively return fields.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpHistoryRequest) Reset() {
	*x = DumpHistoryRequest{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpHistoryRequest) ProtoMessage() {}

func (x *DumpHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpHistoryRequest.ProtoReflect.Descriptor instead.
func (*DumpHistoryRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *DumpHistoryRequest) GetStartToken() *BlockRef {
	if x != nil {
		return x.StartToken
	}
	return nil
}

func (x *DumpHistoryRequest) GetMaxItems() uint32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *DumpHistoryRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response containing the dumped block history.
type DumpHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []*AnyChainBlock       `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"`                          // List of blocks in the history.
	NextToken     *BlockRef              `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"` // Next token for pagination.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpHistoryResponse) Reset() {
	*x = DumpHistoryResponse{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpHistoryResponse) ProtoMessage() {}

func (x *DumpHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpHistoryResponse.ProtoReflect.Descriptor instead.
func (*DumpHistoryResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *DumpHistoryResponse) GetBlock() []*AnyChainBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *DumpHistoryResponse) GetNextToken() *BlockRef {
	if x != nil {
		return x.NextToken
	}
	return nil
}

// Request to follow the tip of the blockchain.
type FollowTipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intersect     []*BlockRef            `protobuf:"bytes,1,rep,name=intersect,proto3" json:"intersect,omitempty"`                  // List of block references to find the intersection.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowTipRequest) Reset() {
	*x = FollowTipRequest{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowTipRequest) ProtoMessage() {}

func (x *FollowTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowTipRequest.ProtoReflect.Descriptor instead.
func (*FollowTipRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{6}
}

func (x *FollowTipRequest) GetIntersect() []*BlockRef {
	if x != nil {
		return x.Intersect
	}
	return nil
}

func (x *FollowTipRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response containing the action to perform while following the tip.
type FollowTipResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*FollowTipResponse_Apply
	//	*FollowTipResponse_Undo
	//	*FollowTipResponse_Reset_
	Action        isFollowTipResponse_Action `protobuf_oneof:"action"`
	Tip           *BlockRef                  `protobuf:"bytes,4,opt,name=tip,proto3" json:"tip,omitempty"` // The current tip of the blockchain after this action.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowTipResponse) Reset() {
	*x = FollowTipResponse{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowTipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowTipResponse) ProtoMessage() {}

func (x *FollowTipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowTipResponse.ProtoReflect.Descriptor instead.
func (*FollowTipResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{7}
}

func (x *FollowTipResponse) GetAction() isFollowTipResponse_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *FollowTipResponse) GetApply() *AnyChainBlock {
	if x != nil {
		if x, ok := x.Action.(*FollowTipResponse_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *FollowTipResponse) GetUndo() *AnyChainBlock {
	if x != nil {
		if x, ok := x.Action.(*FollowTipResponse_Undo); ok {
			return x.Undo
		}
	}
	return nil
}

func (x *FollowTipResponse) GetReset_() *BlockRef {
	if x != nil {
		if x, ok := x.Action.(*FollowTipResponse_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *FollowTipResponse) GetTip() *BlockRef {
	if x != nil {
		return x.Tip
	}
	return nil
}

type isFollowTipResponse_Action interface {
	isFollowTipResponse_Action()
}

type FollowTipResponse_Apply struct {
	Apply *AnyChainBlock `protobuf:"bytes,1,opt,name=apply,proto3,oneof"` // Apply this block.
}

type FollowTipResponse_Undo struct {
	Undo *AnyChainBlock `protobuf:"bytes,2,opt,name=undo,proto3,oneof"` // Undo this block.
}

type FollowTipResponse_Reset_ struct {
	Reset_ *BlockRef `protobuf:"bytes,3,opt,name=reset,proto3,oneof"` // Reset to this block reference.
}

func (*FollowTipResponse_Apply) isFollowTipResponse_Action() {}

func (*FollowTipResponse_Undo) isFollowTipResponse_Action() {}

func (*FollowTipResponse_Reset_) isFollowTipResponse_Action() {}

// Request to read the current tip of the blockchain.
type ReadTipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTipRequest) Reset() {
	*x = ReadTipRequest{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTipRequest) ProtoMessage() {}

func (x *ReadTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTipRequest.ProtoReflect.Descriptor instead.
func (*ReadTipRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{8}
}

// Response containing the current tip of the blockchain.
type ReadTipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tip           *BlockRef              `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"` // The current tip of the blockchain.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTipResponse) Reset() {
	*x = ReadTipResponse{}
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTipResponse) ProtoMessage() {}

func (x *ReadTipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_sync_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTipResponse.ProtoReflect.Descriptor instead.
func (*ReadTipResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ReadTipResponse) GetTip() *BlockRef {
	if x != nil {
		return x.Tip
	}
	return nil
}

var File_utxorpc_v1alpha_sync_sync_proto protoreflect.FileDescriptor

const file_utxorpc_v1alpha_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x1futxorpc/v1alpha/sync/sync.proto\x12\x14utxorpc.v1alpha.sync\x1a google/protobuf/field_mask.proto\x1a%utxorpc/v1alpha/cardano/cardano.proto\"h\n" +
	"\bBlockRef\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"w\n" +
	"\rAnyChainBlock\x12!\n" +
	"\fnative_bytes\x18\x01 \x01(\fR\vnativeBytes\x12:\n" +
	"\acardano\x18\x02 \x01(\v2\x1e.utxorpc.v1alpha.cardano.BlockH\x00R\acardanoB\a\n" +
	"\x05chain\"\x80\x01\n" +
	"\x11FetchBlockRequest\x120\n" +
	"\x03ref\x18\x01 \x03(\v2\x1e.utxorpc.v1alpha.sync.BlockRefR\x03ref\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"O\n" +
	"\x12FetchBlockResponse\x129\n" +
	"\x05block\x18\x01 \x03(\v2#.utxorpc.v1alpha.sync.AnyChainBlockR\x05block\"\xad\x01\n" +
	"\x12DumpHistoryRequest\x12?\n" +
	"\vstart_token\x18\x02 \x01(\v2\x1e.utxorpc.v1alpha.sync.BlockRefR\n" +
	"startToken\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\rR\bmaxItems\x129\n" +
	"\n" +
	"field_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\x8f\x01\n" +
	"\x13DumpHistoryResponse\x129\n" +
	"\x05block\x18\x01 \x03(\v2#.utxorpc.v1alpha.sync.AnyChainBlockR\x05block\x12=\n" +
	"\n" +
	"next_token\x18\x02 \x01(\v2\x1e.utxorpc.v1alpha.sync.BlockRefR\tnextToken\"\x8b\x01\n" +
	"\x10FollowTipRequest\x12<\n" +
	"\tintersect\x18\x01 \x03(\v2\x1e.utxorpc.v1alpha.sync.BlockRefR\tintersect\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\xff\x01\n" +
	"\x11FollowTipResponse\x12;\n" +
	"\x05apply\x18\x01 \x01(\v2#.utxorpc.v1alpha.sync.AnyChainBlockH\x00R\x05apply\x129\n" +
	"\x04undo\x18\x02 \x01(\v2#.utxorpc.v1alpha.sync.AnyChainBlockH\x00R\x04undo\x126\n" +
	"\x05reset\x18\x03 \x01(\v2\x1e.utxorpc.v1alpha.sync.BlockRefH\x00R\x05reset\x120\n" +
	"\x03tip\x18\x04 \x01(\v2\x1e.utxorpc.v1alpha.sync.BlockRefR\x03tipB\b\n" +
	"\x06action\"\x10\n" +
	"\x0eReadTipRequest\"C\n" +
	"\x0fReadTipResponse\x120\n" +
	"\x03tip\x18\x01 \x01(\v2\x1e.utxorpc.v1alpha.sync.BlockRefR\x03tip2\x8a\x03\n" +
	"\vSyncService\x12_\n" +
	"\n" +
	"FetchBlock\x12'.utxorpc.v1alpha.sync.FetchBlockRequest\x1a(.utxorpc.v1alpha.sync.FetchBlockResponse\x12b\n" +
	"\vDumpHistory\x12(.utxorpc.v1alpha.sync.DumpHistoryRequest\x1a).utxorpc.v1alpha.sync.DumpHistoryResponse\x12^\n" +
	"\tFollowTip\x12&.utxorpc.v1alpha.sync.FollowTipRequest\x1a'.utxorpc.v1alpha.sync.FollowTipResponse0\x01\x12V\n" +
	"\aReadTip\x12$.utxorpc.v1alpha.sync.ReadTipRequest\x1a%.utxorpc.v1alpha.sync.ReadTipResponseB\xcb\x01\n" +
	"\x18com.utxorpc.v1alpha.syncB\tSyncProtoP\x01Z2github.com/utxorpc/go-codegen/utxorpc/v1alpha/sync\xa2\x02\x03UVS\xaa\x02\x14Utxorpc.V1alpha.Sync\xca\x02\x14Utxorpc\\V1alpha\\Sync\xe2\x02 Utxorpc\\V1alpha\\Sync\\GPBMetadata\xea\x02\x16Utxorpc::V1alpha::Syncb\x06proto3"

var (
	file_utxorpc_v1alpha_sync_sync_proto_rawDescOnce sync.Once
	file_utxorpc_v1alpha_sync_sync_proto_rawDescData []byte
)

func file_utxorpc_v1alpha_sync_sync_proto_rawDescGZIP() []byte {
	file_utxorpc_v1alpha_sync_sync_proto_rawDescOnce.Do(func() {
		file_utxorpc_v1alpha_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utxorpc_v1alpha_sync_sync_proto_rawDesc), len(file_utxorpc_v1alpha_sync_sync_proto_rawDesc)))
	})
	return file_utxorpc_v1alpha_sync_sync_proto_rawDescData
}

var file_utxorpc_v1alpha_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_utxorpc_v1alpha_sync_sync_proto_goTypes = []any{
	(*BlockRef)(nil),              // 0: utxorpc.v1alpha.sync.BlockRef
	(*AnyChainBlock)(nil),         // 1: utxorpc.v1alpha.sync.AnyChainBlock
	(*FetchBlockRequest)(nil),     // 2: utxorpc.v1alpha.sync.FetchBlockRequest
	(*FetchBlockResponse)(nil),    // 3: utxorpc.v1alpha.sync.FetchBlockResponse
	(*DumpHistoryRequest)(nil),    // 4: utxorpc.v1alpha.sync.DumpHistoryRequest
	(*DumpHistoryResponse)(nil),   // 5: utxorpc.v1alpha.sync.DumpHistoryResponse
	(*FollowTipRequest)(nil),      // 6: utxorpc.v1alpha.sync.FollowTipRequest
	(*FollowTipResponse)(nil),     // 7: utxorpc.v1alpha.sync.FollowTipResponse
	(*ReadTipRequest)(nil),        // 8: utxorpc.v1alpha.sync.ReadTipRequest
	(*ReadTipResponse)(nil),       // 9: utxorpc.v1alpha.sync.ReadTipResponse
	(*cardano.Block)(nil),         // 10: utxorpc.v1alpha.cardano.Block
	(*fieldmaskpb.FieldMask)(nil), // 11: google.protobuf.FieldMask
}
var file_utxorpc_v1alpha_sync_sync_proto_depIdxs = []int32{
	10, // 0: utxorpc.v1alpha.sync.AnyChainBlock.cardano:type_name -> utxorpc.v1alpha.cardano.Block
	0,  // 1: utxorpc.v1alpha.sync.FetchBlockRequest.ref:type_name -> utxorpc.v1alpha.sync.BlockRef
	11, // 2: utxorpc.v1alpha.sync.FetchBlockRequest.field_mask:type_name -> google.protobuf.FieldMask
	1,  // 3: utxorpc.v1alpha.sync.FetchBlockResponse.block:type_name -> utxorpc.v1alpha.sync.AnyChainBlock
	0,  // 4: utxorpc.v1alpha.sync.DumpHistoryRequest.start_token:type_name -> utxorpc.v1alpha.sync.BlockRef
	11, // 5: utxorpc.v1alpha.sync.DumpHistoryRequest.field_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: utxorpc.v1alpha.sync.DumpHistoryResponse.block:type_name -> utxorpc.v1alpha.sync.AnyChainBlock
	0,  // 7: utxorpc.v1alpha.sync.DumpHistoryResponse.next_token:type_name -> utxorpc.v1alpha.sync.BlockRef
	0,  // 8: utxorpc.v1alpha.sync.FollowTipRequest.intersect:type_name -> utxorpc.v1alpha.sync.BlockRef
	11, // 9: utxorpc.v1alpha.sync.FollowTipRequest.field_mask:type_name -> google.protobuf.FieldMask
	1,  // 10: utxorpc.v1alpha.sync.FollowTipResponse.apply:type_name -> utxorpc.v1alpha.sync.AnyChainBlock
	1,  // 11: utxorpc.v1alpha.sync.FollowTipResponse.undo:type_name -> utxorpc.v1alpha.sync.AnyChainBlock
	0,  // 12: utxorpc.v1alpha.sync.FollowTipResponse.reset:type_name -> utxorpc.v1alpha.sync.BlockRef
	0,  // 13: utxorpc.v1alpha.sync.FollowTipResponse.tip:type_name -> utxorpc.v1alpha.sync.BlockRef
	0,  // 14: utxorpc.v1alpha.sync.ReadTipResponse.tip:type_name -> utxorpc.v1alpha.sync.BlockRef
	2,  // 15: utxorpc.v1alpha.sync.SyncService.FetchBlock:input_type -> utxorpc.v1alpha.sync.FetchBlockRequest
	4,  // 16: utxorpc.v1alpha.sync.SyncService.DumpHistory:input_type -> utxorpc.v1alpha.sync.DumpHistoryRequest
	6,  // 17: utxorpc.v1alpha.sync.SyncService.FollowTip:input_type -> utxorpc.v1alpha.sync.FollowTipRequest
	8,  // 18: utxorpc.v1alpha.sync.SyncService.ReadTip:input_type -> utxorpc.v1alpha.sync.ReadTipRequest
	3,  // 19: utxorpc.v1alpha.sync.SyncService.FetchBlock:output_type -> utxorpc.v1alpha.sync.FetchBlockResponse
	5,  // 20: utxorpc.v1alpha.sync.SyncService.DumpHistory:output_type -> utxorpc.v1alpha.sync.DumpHistoryResponse
	7,  // 21: utxorpc.v1alpha.sync.SyncService.FollowTip:output_type -> utxorpc.v1alpha.sync.FollowTipResponse
	9,  // 22: utxorpc.v1alpha.sync.SyncService.ReadTip:output_type -> utxorpc.v1alpha.sync.ReadTipResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_utxorpc_v1alpha_sync_sync_proto_init() }
func file_utxorpc_v1alpha_sync_sync_proto_init() {
	if File_utxorpc_v1alpha_sync_sync_proto != nil {
		return
	}
	file_utxorpc_v1alpha_sync_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*AnyChainBlock_Cardano)(nil),
	}
	file_utxorpc_v1alpha_sync_sync_proto_msgTypes[7].OneofWrappers = []any{
		(*FollowTipResponse_Apply)(nil),
		(*FollowTipResponse_Undo)(nil),
		(*FollowTipResponse_Reset_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utxorpc_v1alpha_sync_sync_proto_rawDesc), len(file_utxorpc_v1alpha_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utxorpc_v1alpha_sync_sync_proto_goTypes,
		DependencyIndexes: file_utxorpc_v1alpha_sync_sync_proto_depIdxs,
		MessageInfos:      file_utxorpc_v1alpha_sync_sync_proto_msgTypes,
	}.Build()
	File_utxorpc_v1alpha_sync_sync_proto = out.File
	file_utxorpc_v1alpha_sync_sync_proto_goTypes = nil
	file_utxorpc_v1alpha_sync_sync_proto_depIdxs = nil
}
