// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: utxorpc/v1alpha/submit/submit.proto

package submit

import (
	cardano "github.com/utxorpc/go-codegen/utxorpc/v1alpha/cardano"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum representing the various stages of a transaction's lifecycle.
type Stage int32

const (
	Stage_STAGE_UNSPECIFIED  Stage = 0 // Unspecified stage.
	Stage_STAGE_ACKNOWLEDGED Stage = 1 // Transaction has been acknowledged by the node.
	Stage_STAGE_MEMPOOL      Stage = 2 // Transaction is in the mempool.
	Stage_STAGE_NETWORK      Stage = 3 // Transaction has been propagated across the network.
	Stage_STAGE_CONFIRMED    Stage = 4 // Transaction has been confirmed on the blockchain.
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_ACKNOWLEDGED",
		2: "STAGE_MEMPOOL",
		3: "STAGE_NETWORK",
		4: "STAGE_CONFIRMED",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED":  0,
		"STAGE_ACKNOWLEDGED": 1,
		"STAGE_MEMPOOL":      2,
		"STAGE_NETWORK":      3,
		"STAGE_CONFIRMED":    4,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_utxorpc_v1alpha_submit_submit_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_utxorpc_v1alpha_submit_submit_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{0}
}

// Represents a transaction from any supported blockchain.
type AnyChainTx struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*AnyChainTx_Raw
	Type          isAnyChainTx_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainTx) Reset() {
	*x = AnyChainTx{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainTx) ProtoMessage() {}

func (x *AnyChainTx) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainTx.ProtoReflect.Descriptor instead.
func (*AnyChainTx) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{0}
}

func (x *AnyChainTx) GetType() isAnyChainTx_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AnyChainTx) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Type.(*AnyChainTx_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isAnyChainTx_Type interface {
	isAnyChainTx_Type()
}

type AnyChainTx_Raw struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3,oneof"` // Raw transaction data.
}

func (*AnyChainTx_Raw) isAnyChainTx_Type() {}

// Request to evaluate transactions without submitting.
type EvalTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []*AnyChainTx          `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"` // List of transactions to evaluate.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalTxRequest) Reset() {
	*x = EvalTxRequest{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalTxRequest) ProtoMessage() {}

func (x *EvalTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalTxRequest.ProtoReflect.Descriptor instead.
func (*EvalTxRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{1}
}

func (x *EvalTxRequest) GetTx() []*AnyChainTx {
	if x != nil {
		return x.Tx
	}
	return nil
}

// Report containing the result of evaluating a particular transaction
type AnyChainEval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chain:
	//
	//	*AnyChainEval_Cardano
	Chain         isAnyChainEval_Chain `protobuf_oneof:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainEval) Reset() {
	*x = AnyChainEval{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainEval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainEval) ProtoMessage() {}

func (x *AnyChainEval) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainEval.ProtoReflect.Descriptor instead.
func (*AnyChainEval) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{2}
}

func (x *AnyChainEval) GetChain() isAnyChainEval_Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *AnyChainEval) GetCardano() *cardano.TxEval {
	if x != nil {
		if x, ok := x.Chain.(*AnyChainEval_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyChainEval_Chain interface {
	isAnyChainEval_Chain()
}

type AnyChainEval_Cardano struct {
	Cardano *cardano.TxEval `protobuf:"bytes,1,opt,name=cardano,proto3,oneof"` // A Cardano tx evaluation report.
}

func (*AnyChainEval_Cardano) isAnyChainEval_Chain() {}

// Response containing the reports form the transaction evaluation.
type EvalTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        []*AnyChainEval        `protobuf:"bytes,1,rep,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalTxResponse) Reset() {
	*x = EvalTxResponse{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalTxResponse) ProtoMessage() {}

func (x *EvalTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalTxResponse.ProtoReflect.Descriptor instead.
func (*EvalTxResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{3}
}

func (x *EvalTxResponse) GetReport() []*AnyChainEval {
	if x != nil {
		return x.Report
	}
	return nil
}

// Request to submit transactions to the blockchain.
type SubmitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []*AnyChainTx          `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"` // List of transactions to submit.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxRequest) Reset() {
	*x = SubmitTxRequest{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxRequest) ProtoMessage() {}

func (x *SubmitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxRequest.ProtoReflect.Descriptor instead.
func (*SubmitTxRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitTxRequest) GetTx() []*AnyChainTx {
	if x != nil {
		return x.Tx
	}
	return nil
}

// Response containing references to the submitted transactions.
type SubmitTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           [][]byte               `protobuf:"bytes,1,rep,name=ref,proto3" json:"ref,omitempty"` // List of transaction references.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxResponse) Reset() {
	*x = SubmitTxResponse{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxResponse) ProtoMessage() {}

func (x *SubmitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxResponse.ProtoReflect.Descriptor instead.
func (*SubmitTxResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitTxResponse) GetRef() [][]byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

type TxInMempool struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Ref         []byte                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`                                        // The transaction reference.
	NativeBytes []byte                 `protobuf:"bytes,2,opt,name=native_bytes,json=nativeBytes,proto3" json:"native_bytes,omitempty"`     // Original bytes as defined by the chain
	Stage       Stage                  `protobuf:"varint,3,opt,name=stage,proto3,enum=utxorpc.v1alpha.submit.Stage" json:"stage,omitempty"` // The current stage of the tx
	// Types that are valid to be assigned to ParsedState:
	//
	//	*TxInMempool_Cardano
	ParsedState   isTxInMempool_ParsedState `protobuf_oneof:"parsed_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInMempool) Reset() {
	*x = TxInMempool{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInMempool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInMempool) ProtoMessage() {}

func (x *TxInMempool) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInMempool.ProtoReflect.Descriptor instead.
func (*TxInMempool) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{6}
}

func (x *TxInMempool) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *TxInMempool) GetNativeBytes() []byte {
	if x != nil {
		return x.NativeBytes
	}
	return nil
}

func (x *TxInMempool) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *TxInMempool) GetParsedState() isTxInMempool_ParsedState {
	if x != nil {
		return x.ParsedState
	}
	return nil
}

func (x *TxInMempool) GetCardano() *cardano.Tx {
	if x != nil {
		if x, ok := x.ParsedState.(*TxInMempool_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isTxInMempool_ParsedState interface {
	isTxInMempool_ParsedState()
}

type TxInMempool_Cardano struct {
	Cardano *cardano.Tx `protobuf:"bytes,4,opt,name=cardano,proto3,oneof"` // A Cardano transaction.
}

func (*TxInMempool_Cardano) isTxInMempool_ParsedState() {}

// Request to check the status of submitted transactions.
type ReadMempoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMempoolRequest) Reset() {
	*x = ReadMempoolRequest{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMempoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMempoolRequest) ProtoMessage() {}

func (x *ReadMempoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMempoolRequest.ProtoReflect.Descriptor instead.
func (*ReadMempoolRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{7}
}

// Response containing the stage of the submitted transactions.
type ReadMempoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TxInMempool         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // List of transaction currently on the mempool.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMempoolResponse) Reset() {
	*x = ReadMempoolResponse{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMempoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMempoolResponse) ProtoMessage() {}

func (x *ReadMempoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMempoolResponse.ProtoReflect.Descriptor instead.
func (*ReadMempoolResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{8}
}

func (x *ReadMempoolResponse) GetItems() []*TxInMempool {
	if x != nil {
		return x.Items
	}
	return nil
}

// Request to wait for transactions to reach a certain stage.
type WaitForTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           [][]byte               `protobuf:"bytes,1,rep,name=ref,proto3" json:"ref,omitempty"` // List of transaction references to wait for.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForTxRequest) Reset() {
	*x = WaitForTxRequest{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForTxRequest) ProtoMessage() {}

func (x *WaitForTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForTxRequest.ProtoReflect.Descriptor instead.
func (*WaitForTxRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{9}
}

func (x *WaitForTxRequest) GetRef() [][]byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

// Response containing the transaction reference and stage once it has been reached.
type WaitForTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           []byte                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`                                        // Transaction reference.
	Stage         Stage                  `protobuf:"varint,2,opt,name=stage,proto3,enum=utxorpc.v1alpha.submit.Stage" json:"stage,omitempty"` // Stage reached by the transaction.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForTxResponse) Reset() {
	*x = WaitForTxResponse{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForTxResponse) ProtoMessage() {}

func (x *WaitForTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForTxResponse.ProtoReflect.Descriptor instead.
func (*WaitForTxResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{10}
}

func (x *WaitForTxResponse) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *WaitForTxResponse) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

// Represents a tx pattern from any supported blockchain.
type AnyChainTxPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chain:
	//
	//	*AnyChainTxPattern_Cardano
	Chain         isAnyChainTxPattern_Chain `protobuf_oneof:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyChainTxPattern) Reset() {
	*x = AnyChainTxPattern{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyChainTxPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyChainTxPattern) ProtoMessage() {}

func (x *AnyChainTxPattern) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyChainTxPattern.ProtoReflect.Descriptor instead.
func (*AnyChainTxPattern) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{11}
}

func (x *AnyChainTxPattern) GetChain() isAnyChainTxPattern_Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *AnyChainTxPattern) GetCardano() *cardano.TxPattern {
	if x != nil {
		if x, ok := x.Chain.(*AnyChainTxPattern_Cardano); ok {
			return x.Cardano
		}
	}
	return nil
}

type isAnyChainTxPattern_Chain interface {
	isAnyChainTxPattern_Chain()
}

type AnyChainTxPattern_Cardano struct {
	Cardano *cardano.TxPattern `protobuf:"bytes,1,opt,name=cardano,proto3,oneof"` // A Cardano tx pattern.
}

func (*AnyChainTxPattern_Cardano) isAnyChainTxPattern_Chain() {}

// Represents a simple tx predicate that can composed to create more complex ones
type TxPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *AnyChainTxPattern     `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`              // Predicate is true if tx exhibits pattern.
	Not           []*TxPredicate         `protobuf:"bytes,2,rep,name=not,proto3" json:"not,omitempty"`                  // Predicate is true if tx doesn't exhibit pattern.
	AllOf         []*TxPredicate         `protobuf:"bytes,3,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"` // Predicate is true if tx exhibits all of the patterns.
	AnyOf         []*TxPredicate         `protobuf:"bytes,4,rep,name=any_of,json=anyOf,proto3" json:"any_of,omitempty"` // Predicate is true if tx exhibits any of the patterns.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxPredicate) Reset() {
	*x = TxPredicate{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPredicate) ProtoMessage() {}

func (x *TxPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPredicate.ProtoReflect.Descriptor instead.
func (*TxPredicate) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{12}
}

func (x *TxPredicate) GetMatch() *AnyChainTxPattern {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *TxPredicate) GetNot() []*TxPredicate {
	if x != nil {
		return x.Not
	}
	return nil
}

func (x *TxPredicate) GetAllOf() []*TxPredicate {
	if x != nil {
		return x.AllOf
	}
	return nil
}

func (x *TxPredicate) GetAnyOf() []*TxPredicate {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

// Request to watch changes of specific mempool txs.
type WatchMempoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predicate     *TxPredicate           `protobuf:"bytes,1,opt,name=predicate,proto3" json:"predicate,omitempty"`                  // A predicate to filter transactions by.
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"` // Field mask to selectively return fields.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMempoolRequest) Reset() {
	*x = WatchMempoolRequest{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMempoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMempoolRequest) ProtoMessage() {}

func (x *WatchMempoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMempoolRequest.ProtoReflect.Descriptor instead.
func (*WatchMempoolRequest) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{13}
}

func (x *WatchMempoolRequest) GetPredicate() *TxPredicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *WatchMempoolRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

// Response that represents a change in a mempool tx.
type WatchMempoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *TxInMempool           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"` // The content and stage of the tx that has changed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMempoolResponse) Reset() {
	*x = WatchMempoolResponse{}
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMempoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMempoolResponse) ProtoMessage() {}

func (x *WatchMempoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utxorpc_v1alpha_submit_submit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMempoolResponse.ProtoReflect.Descriptor instead.
func (*WatchMempoolResponse) Descriptor() ([]byte, []int) {
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP(), []int{14}
}

func (x *WatchMempoolResponse) GetTx() *TxInMempool {
	if x != nil {
		return x.Tx
	}
	return nil
}

var File_utxorpc_v1alpha_submit_submit_proto protoreflect.FileDescriptor

const file_utxorpc_v1alpha_submit_submit_proto_rawDesc = "" +
	"\n" +
	"#utxorpc/v1alpha/submit/submit.proto\x12\x16utxorpc.v1alpha.submit\x1a google/protobuf/field_mask.proto\x1a%utxorpc/v1alpha/cardano/cardano.proto\"(\n" +
	"\n" +
	"AnyChainTx\x12\x12\n" +
	"\x03raw\x18\x01 \x01(\fH\x00R\x03rawB\x06\n" +
	"\x04type\"C\n" +
	"\rEvalTxRequest\x122\n" +
	"\x02tx\x18\x01 \x03(\v2\".utxorpc.v1alpha.submit.AnyChainTxR\x02tx\"T\n" +
	"\fAnyChainEval\x12;\n" +
	"\acardano\x18\x01 \x01(\v2\x1f.utxorpc.v1alpha.cardano.TxEvalH\x00R\acardanoB\a\n" +
	"\x05chain\"N\n" +
	"\x0eEvalTxResponse\x12<\n" +
	"\x06report\x18\x01 \x03(\v2$.utxorpc.v1alpha.submit.AnyChainEvalR\x06report\"E\n" +
	"\x0fSubmitTxRequest\x122\n" +
	"\x02tx\x18\x01 \x03(\v2\".utxorpc.v1alpha.submit.AnyChainTxR\x02tx\"$\n" +
	"\x10SubmitTxResponse\x12\x10\n" +
	"\x03ref\x18\x01 \x03(\fR\x03ref\"\xc0\x01\n" +
	"\vTxInMempool\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\fR\x03ref\x12!\n" +
	"\fnative_bytes\x18\x02 \x01(\fR\vnativeBytes\x123\n" +
	"\x05stage\x18\x03 \x01(\x0e2\x1d.utxorpc.v1alpha.submit.StageR\x05stage\x127\n" +
	"\acardano\x18\x04 \x01(\v2\x1b.utxorpc.v1alpha.cardano.TxH\x00R\acardanoB\x0e\n" +
	"\fparsed_state\"\x14\n" +
	"\x12ReadMempoolRequest\"P\n" +
	"\x13ReadMempoolResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.utxorpc.v1alpha.submit.TxInMempoolR\x05items\"$\n" +
	"\x10WaitForTxRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x03(\fR\x03ref\"Z\n" +
	"\x11WaitForTxResponse\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\fR\x03ref\x123\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x1d.utxorpc.v1alpha.submit.StageR\x05stage\"\\\n" +
	"\x11AnyChainTxPattern\x12>\n" +
	"\acardano\x18\x01 \x01(\v2\".utxorpc.v1alpha.cardano.TxPatternH\x00R\acardanoB\a\n" +
	"\x05chain\"\xfd\x01\n" +
	"\vTxPredicate\x12?\n" +
	"\x05match\x18\x01 \x01(\v2).utxorpc.v1alpha.submit.AnyChainTxPatternR\x05match\x125\n" +
	"\x03not\x18\x02 \x03(\v2#.utxorpc.v1alpha.submit.TxPredicateR\x03not\x12:\n" +
	"\x06all_of\x18\x03 \x03(\v2#.utxorpc.v1alpha.submit.TxPredicateR\x05allOf\x12:\n" +
	"\x06any_of\x18\x04 \x03(\v2#.utxorpc.v1alpha.submit.TxPredicateR\x05anyOf\"\x93\x01\n" +
	"\x13WatchMempoolRequest\x12A\n" +
	"\tpredicate\x18\x01 \x01(\v2#.utxorpc.v1alpha.submit.TxPredicateR\tpredicate\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"K\n" +
	"\x14WatchMempoolResponse\x123\n" +
	"\x02tx\x18\x01 \x01(\v2#.utxorpc.v1alpha.submit.TxInMempoolR\x02tx*q\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STAGE_ACKNOWLEDGED\x10\x01\x12\x11\n" +
	"\rSTAGE_MEMPOOL\x10\x02\x12\x11\n" +
	"\rSTAGE_NETWORK\x10\x03\x12\x13\n" +
	"\x0fSTAGE_CONFIRMED\x10\x042\x80\x04\n" +
	"\rSubmitService\x12W\n" +
	"\x06EvalTx\x12%.utxorpc.v1alpha.submit.EvalTxRequest\x1a&.utxorpc.v1alpha.submit.EvalTxResponse\x12]\n" +
	"\bSubmitTx\x12'.utxorpc.v1alpha.submit.SubmitTxRequest\x1a(.utxorpc.v1alpha.submit.SubmitTxResponse\x12b\n" +
	"\tWaitForTx\x12(.utxorpc.v1alpha.submit.WaitForTxRequest\x1a).utxorpc.v1alpha.submit.WaitForTxResponse0\x01\x12f\n" +
	"\vReadMempool\x12*.utxorpc.v1alpha.submit.ReadMempoolRequest\x1a+.utxorpc.v1alpha.submit.ReadMempoolResponse\x12k\n" +
	"\fWatchMempool\x12+.utxorpc.v1alpha.submit.WatchMempoolRequest\x1a,.utxorpc.v1alpha.submit.WatchMempoolResponse0\x01B\xd9\x01\n" +
	"\x1acom.utxorpc.v1alpha.submitB\vSubmitProtoP\x01Z4github.com/utxorpc/go-codegen/utxorpc/v1alpha/submit\xa2\x02\x03UVS\xaa\x02\x16Utxorpc.V1alpha.Submit\xca\x02\x16Utxorpc\\V1alpha\\Submit\xe2\x02\"Utxorpc\\V1alpha\\Submit\\GPBMetadata\xea\x02\x18Utxorpc::V1alpha::Submitb\x06proto3"

var (
	file_utxorpc_v1alpha_submit_submit_proto_rawDescOnce sync.Once
	file_utxorpc_v1alpha_submit_submit_proto_rawDescData []byte
)

func file_utxorpc_v1alpha_submit_submit_proto_rawDescGZIP() []byte {
	file_utxorpc_v1alpha_submit_submit_proto_rawDescOnce.Do(func() {
		file_utxorpc_v1alpha_submit_submit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utxorpc_v1alpha_submit_submit_proto_rawDesc), len(file_utxorpc_v1alpha_submit_submit_proto_rawDesc)))
	})
	return file_utxorpc_v1alpha_submit_submit_proto_rawDescData
}

var file_utxorpc_v1alpha_submit_submit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_utxorpc_v1alpha_submit_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_utxorpc_v1alpha_submit_submit_proto_goTypes = []any{
	(Stage)(0),                    // 0: utxorpc.v1alpha.submit.Stage
	(*AnyChainTx)(nil),            // 1: utxorpc.v1alpha.submit.AnyChainTx
	(*EvalTxRequest)(nil),         // 2: utxorpc.v1alpha.submit.EvalTxRequest
	(*AnyChainEval)(nil),          // 3: utxorpc.v1alpha.submit.AnyChainEval
	(*EvalTxResponse)(nil),        // 4: utxorpc.v1alpha.submit.EvalTxResponse
	(*SubmitTxRequest)(nil),       // 5: utxorpc.v1alpha.submit.SubmitTxRequest
	(*SubmitTxResponse)(nil),      // 6: utxorpc.v1alpha.submit.SubmitTxResponse
	(*TxInMempool)(nil),           // 7: utxorpc.v1alpha.submit.TxInMempool
	(*ReadMempoolRequest)(nil),    // 8: utxorpc.v1alpha.submit.ReadMempoolRequest
	(*ReadMempoolResponse)(nil),   // 9: utxorpc.v1alpha.submit.ReadMempoolResponse
	(*WaitForTxRequest)(nil),      // 10: utxorpc.v1alpha.submit.WaitForTxRequest
	(*WaitForTxResponse)(nil),     // 11: utxorpc.v1alpha.submit.WaitForTxResponse
	(*AnyChainTxPattern)(nil),     // 12: utxorpc.v1alpha.submit.AnyChainTxPattern
	(*TxPredicate)(nil),           // 13: utxorpc.v1alpha.submit.TxPredicate
	(*WatchMempoolRequest)(nil),   // 14: utxorpc.v1alpha.submit.WatchMempoolRequest
	(*WatchMempoolResponse)(nil),  // 15: utxorpc.v1alpha.submit.WatchMempoolResponse
	(*cardano.TxEval)(nil),        // 16: utxorpc.v1alpha.cardano.TxEval
	(*cardano.Tx)(nil),            // 17: utxorpc.v1alpha.cardano.Tx
	(*cardano.TxPattern)(nil),     // 18: utxorpc.v1alpha.cardano.TxPattern
	(*fieldmaskpb.FieldMask)(nil), // 19: google.protobuf.FieldMask
}
var file_utxorpc_v1alpha_submit_submit_proto_depIdxs = []int32{
	1,  // 0: utxorpc.v1alpha.submit.EvalTxRequest.tx:type_name -> utxorpc.v1alpha.submit.AnyChainTx
	16, // 1: utxorpc.v1alpha.submit.AnyChainEval.cardano:type_name -> utxorpc.v1alpha.cardano.TxEval
	3,  // 2: utxorpc.v1alpha.submit.EvalTxResponse.report:type_name -> utxorpc.v1alpha.submit.AnyChainEval
	1,  // 3: utxorpc.v1alpha.submit.SubmitTxRequest.tx:type_name -> utxorpc.v1alpha.submit.AnyChainTx
	0,  // 4: utxorpc.v1alpha.submit.TxInMempool.stage:type_name -> utxorpc.v1alpha.submit.Stage
	17, // 5: utxorpc.v1alpha.submit.TxInMempool.cardano:type_name -> utxorpc.v1alpha.cardano.Tx
	7,  // 6: utxorpc.v1alpha.submit.ReadMempoolResponse.items:type_name -> utxorpc.v1alpha.submit.TxInMempool
	0,  // 7: utxorpc.v1alpha.submit.WaitForTxResponse.stage:type_name -> utxorpc.v1alpha.submit.Stage
	18, // 8: utxorpc.v1alpha.submit.AnyChainTxPattern.cardano:type_name -> utxorpc.v1alpha.cardano.TxPattern
	12, // 9: utxorpc.v1alpha.submit.TxPredicate.match:type_name -> utxorpc.v1alpha.submit.AnyChainTxPattern
	13, // 10: utxorpc.v1alpha.submit.TxPredicate.not:type_name -> utxorpc.v1alpha.submit.TxPredicate
	13, // 11: utxorpc.v1alpha.submit.TxPredicate.all_of:type_name -> utxorpc.v1alpha.submit.TxPredicate
	13, // 12: utxorpc.v1alpha.submit.TxPredicate.any_of:type_name -> utxorpc.v1alpha.submit.TxPredicate
	13, // 13: utxorpc.v1alpha.submit.WatchMempoolRequest.predicate:type_name -> utxorpc.v1alpha.submit.TxPredicate
	19, // 14: utxorpc.v1alpha.submit.WatchMempoolRequest.field_mask:type_name -> google.protobuf.FieldMask
	7,  // 15: utxorpc.v1alpha.submit.WatchMempoolResponse.tx:type_name -> utxorpc.v1alpha.submit.TxInMempool
	2,  // 16: utxorpc.v1alpha.submit.SubmitService.EvalTx:input_type -> utxorpc.v1alpha.submit.EvalTxRequest
	5,  // 17: utxorpc.v1alpha.submit.SubmitService.SubmitTx:input_type -> utxorpc.v1alpha.submit.SubmitTxRequest
	10, // 18: utxorpc.v1alpha.submit.SubmitService.WaitForTx:input_type -> utxorpc.v1alpha.submit.WaitForTxRequest
	8,  // 19: utxorpc.v1alpha.submit.SubmitService.ReadMempool:input_type -> utxorpc.v1alpha.submit.ReadMempoolRequest
	14, // 20: utxorpc.v1alpha.submit.SubmitService.WatchMempool:input_type -> utxorpc.v1alpha.submit.WatchMempoolRequest
	4,  // 21: utxorpc.v1alpha.submit.SubmitService.EvalTx:output_type -> utxorpc.v1alpha.submit.EvalTxResponse
	6,  // 22: utxorpc.v1alpha.submit.SubmitService.SubmitTx:output_type -> utxorpc.v1alpha.submit.SubmitTxResponse
	11, // 23: utxorpc.v1alpha.submit.SubmitService.WaitForTx:output_type -> utxorpc.v1alpha.submit.WaitForTxResponse
	9,  // 24: utxorpc.v1alpha.submit.SubmitService.ReadMempool:output_type -> utxorpc.v1alpha.submit.ReadMempoolResponse
	15, // 25: utxorpc.v1alpha.submit.SubmitService.WatchMempool:output_type -> utxorpc.v1alpha.submit.WatchMempoolResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_utxorpc_v1alpha_submit_submit_proto_init() }
func file_utxorpc_v1alpha_submit_submit_proto_init() {
	if File_utxorpc_v1alpha_submit_submit_proto != nil {
		return
	}
	file_utxorpc_v1alpha_submit_submit_proto_msgTypes[0].OneofWrappers = []any{
		(*AnyChainTx_Raw)(nil),
	}
	file_utxorpc_v1alpha_submit_submit_proto_msgTypes[2].OneofWrappers = []any{
		(*AnyChainEval_Cardano)(nil),
	}
	file_utxorpc_v1alpha_submit_submit_proto_msgTypes[6].OneofWrappers = []any{
		(*TxInMempool_Cardano)(nil),
	}
	file_utxorpc_v1alpha_submit_submit_proto_msgTypes[11].OneofWrappers = []any{
		(*AnyChainTxPattern_Cardano)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utxorpc_v1alpha_submit_submit_proto_rawDesc), len(file_utxorpc_v1alpha_submit_submit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utxorpc_v1alpha_submit_submit_proto_goTypes,
		DependencyIndexes: file_utxorpc_v1alpha_submit_submit_proto_depIdxs,
		EnumInfos:         file_utxorpc_v1alpha_submit_submit_proto_enumTypes,
		MessageInfos:      file_utxorpc_v1alpha_submit_submit_proto_msgTypes,
	}.Build()
	File_utxorpc_v1alpha_submit_submit_proto = out.File
	file_utxorpc_v1alpha_submit_submit_proto_goTypes = nil
	file_utxorpc_v1alpha_submit_submit_proto_depIdxs = nil
}
